SpecFlowOSS/SpecFlow

Runtime/Assist/TEHelpers.cs
Runtime/Assist/ValueRetrievers/DateTimeOffsetValueRetriever.cs
Runtime/Assist/ValueRetrievers/NullableDateTimeOffsetValueRetriever.cs
Runtime/TechTalk.SpecFlow.csproj
Tests/RuntimeTests/AssistTests/ValueRetrieverTests/DateTimeOffsetValueRetrieverTests.cs
Tests/RuntimeTests/AssistTests/ValueRetrieverTests/NullableDateTimeOffsetValueRetriever.cs
Tests/RuntimeTests/RuntimeTests.csproj

Table -> Object translation was not converting DateTimeOffset table
values.  This should allow the Table Assist helpers to do so.

Issue 193: Adding a new value retriever for DateTimeOffsets

---

.gitignore
Generator/Project/MsBuildProjectFileExtensions.cs
Generator/Project/MsBuildProjectReader.cs
Generator/TechTalk.SpecFlow.Generator.csproj
Tests/GeneratorTests/Data/app.config
Tests/GeneratorTests/Data/sampleCsProjectfile.csproj
Tests/GeneratorTests/GeneratorTests.csproj
Tests/GeneratorTests/MsBuildProjectReaderTests.cs

This fixes the issues with the obsolete MSBuild related classes that were being used to parse the CSProj files in order to generate reports.
No tests existed that i could see for any of this stuff so I added a single characterisation test which parses a sample csproj file and app.config from one of my existing specflow projects. Code was updated to provide the same behaviour, but without using the obsolete classes. Hopefully this covers all the use cases, but without tests its hard to be certain.

Updated usages of obsolete MSBuild project file parsing elements.

---

Tests/RuntimeTests/StronglyTypedContextAcessorTests.cs

Questions and issues like around #392 have come up a few times.
Though this problem has been solved, I saw that the solution was not tested directly.  I wrote two unit tests that match the failing examples from other users.  
Not so much for regressions, but just to make the expected behavior explicit.

Cover null handling around Get<T> and Set<T> directly

---

Runtime/Assist/TEHelpers.cs
Tests/RuntimeTests/AssistTests/CreateInstanceHelperMethodTests.cs

Who would do this?
```c#
private class Snake
{
public string Look_at_me { get; set; }
public string this_is_so_long { get; set; }
}
```
Probably nobody.  Putting a spotlight on how we match columns to properties in #512 made me think that there might be some situations when the properties need to be changed to match the columns... but this is the only case I could think that wouldn't work.

Snake case properties

---

Generator/UnitTestProvider/XUnitTestGeneratorProvider.cs

Setting the Category as a trait attribute, which allows you to include/exclude groups of tests using the /trait or /-trait parameters.
We've used this successfully already via a Specflow plugin, thought we'd see if you'd like to include it in the main Specflow implementation.
Eg.  Include all smoketest categorised tests but exclude broken ones
/trait "Category=smoketest" /-trait "Category=broken"

Added XUnit implementation for SetTestClassCategories using traits

---

Runtime/Assist/Service.cs
Runtime/Assist/ValueRetrievers/DateTimeOffsetValueRetriever.cs
Runtime/Assist/ValueRetrievers/NullableDateTimeOffsetValueRetriever.cs
Runtime/TechTalk.SpecFlow.csproj
Tests/RuntimeTests/AssistTests/ServiceTests.cs
Tests/RuntimeTests/AssistTests/ValueRetrieverTests/DateTimeOffsetValueRetrieverTests.cs
Tests/RuntimeTests/AssistTests/ValueRetrieverTests/NullableDateTimeOffsetValueRetriever.cs
Tests/RuntimeTests/RuntimeTests.csproj

We had datetime offset retrievers for SpecFlow.Assist in the pre-v2 master, thanks to Tim Gebhardt.  I must have screwed up something, somehow, because the two classes were lost in the v2 changes.
So I cherry-picked them back, made them implement the new ```IValueRetriever```, and we should be back to normal!

Bring back the datetime offset retriever that got lost with v2

---

Generator/Plugins/IGeneratorPluginLoader.cs

If you generate the feature.cs - Code Behind files via MSBuild- Task, the GeneratorPluginLoader does not look into the net45 folders and so does not find the plugin.

Load Generator Plugins from net45 folders

---

Runtime/Assist/Service.cs
Runtime/Assist/ValueRetrievers/StepTransformationValueRetriever.cs
Runtime/TechTalk.SpecFlow.csproj
Tests/RuntimeTests/AssistTests/ServiceTests.cs
Tests/RuntimeTests/AssistTests/ValueRetrieverTests/StepTransformationValueRetrieverTests.cs
Tests/RuntimeTests/RuntimeTests.csproj

This feature allows step argument transformations to be used in the SpecFlow.Assist helpers.
For example, let's say you had a StepArgumentTransformation to change a string into a ```Product```.
```c#
[StepArgumentTransformation]
public Product ToProduct(string name)
{
return new Product(name);
}
```
You could then do this:
```gherkin
Given I have these things
| Product |
| a       |
| b       |
```
```c#
public class Thing
{
public Product Product { get; set; }
}
[Given("I have these things")]
public void x(Table table)
{
// the conversion of the strings "a" and "b" will run through
// your step argument transformation
var things = table.CreateSet<Thing>();
things[0].Product.Name; // will equal "a"
things[1].Product.Name; // will equal "b"
}
```
This feature really needs to be …

Step transformation value retriever

---

Tests/RuntimeTests/AssistTests/TableHelperExtensionMethods/CreateSetHelperMethodTests.cs

The behaviour of dashes in column name has changed, but there is no test for that.

Additional assists test

---

Parser/SpecFlowGherkinParser.cs

This is a change needed for SpecFlow+Excel to be upgraded to SpecFlow 2.0.
We need to access the DialectProvider that is used by the SpecFlowGherkinParser.

make DialectProvider public for other Assemblies

---

Runtime/TechTalk.SpecFlow.csproj

there is compile error ".\SpecFlow\Runtime\DictionaryHelpers.cs' could not be found" - file does not exists after last commit deletion

Exclude missing DictionaryHelpers.cs

---

Tools/config.template

Currently the binding redirects are created this way:
<bindingRedirect oldVersion="2.0.0.0-2.1.0" newVersion="2.1.0" />
Which is wrong, because the build number is missing.
<bindingRedirect oldVersion="2.0.0.0-2.1.0.0" newVersion="2.1.0.0" />
This fixes the generation

Fix generation of App.config and plugincompability.config

---

Runtime/Assist/InstanceComparisonExtensionMethods.cs
Runtime/Assist/SetComparer.cs
Tests/RuntimeTests/AssistTests/InstanceComparisonExtensionMethodsTests.cs
Tests/RuntimeTests/AssistTests/InstanceEquivalenceExtensionMethodTests.cs
Tests/RuntimeTests/RuntimeTests.csproj

CompareToSet looks for a matching index, while it's doing that it doesn't need to generate ComparisonExceptions like CompareToInstance does, because prior to this commit they were swallowed just to indicate a non-match.  This caused a lot of gc events in large sets, so this commit dramatically increases performance of CompareToSet in large, un-ordered sets.  For my case it went from 4500 seconds to 23 seconds.
Will also stop evaluating each instance after the first difference is found when all we need to know is if they are different.

Enhance CompareToSet by not using Exceptions through ThisItemIsAMatch

---

Runtime/Assist/EnumerableProjection.cs
Runtime/Assist/InstanceComparisonExtensionMethods.cs
Runtime/Assist/RowExtensionMethods.cs
Runtime/Assist/Service.cs
Runtime/Assist/SetComparer.cs
Runtime/Assist/TEHelpers.cs
Runtime/Assist/TableDiffExceptionBuilder.cs
Runtime/Assist/TableDifferenceResults.cs
Runtime/Assist/ValueComparers/BoolValueComparer.cs
Runtime/Assist/ValueComparers/DateTimeValueComparer.cs
Runtime/Assist/ValueComparers/DecimalValueComparer.cs
Runtime/Assist/ValueComparers/DefaultValueComparer.cs
Runtime/Assist/ValueComparers/DoubleValueComparer.cs
Runtime/Assist/ValueComparers/FloatValueComparer.cs
Runtime/Assist/ValueComparers/GuidValueComparer.cs
Runtime/Assist/ValueRetrievers/EnumValueRetriever.cs
Runtime/Assist/ValueRetrievers/NullableTimeSpanValueRetriever.cs
Runtime/Assist/ValueRetrievers/TimeSpanValueRetriever.cs

Resubmitted as a performance improvement.
- As discussed, rocknet's performance improvements are much larger (4500 seconds to 23 seconds), but it involves a semantic change.
- These changes still improve the performance significantly, from 50 seconds to 27 seconds, but without any semantic change as all differences are still reported in the comparison exception. Attached is the test code (zipped linqpad query)
[MeasureSetComparison.zip](https://github.com/techtalk/SpecFlow/files/245128/MeasureSetComparison.zip)
. Note that I should serialize the test case to a file for repeatably and do multiple runs of course. I did 4 runs; two with each version.
Original:
Finished comparison in 54925 ms.
Finished comparison in 48328 ms.
This branch:
Finished comparison in 26380 ms.
Finished comparison …

Performance improvements to set comparison for large sets.

---

Runtime/Bindings/RegexFactory.cs

As the number of step definitions and their respective regexes becomes sufficiently high (thousands), a performance issue becomes apparent, i.e., heavy startup (in terms of CPU and memory consumption) whereas the performance gains from faster execution speeds of the compiled regexes remain hardly noticeable. 
Removing Compiled regex option resolves the issue.

Regex performance enhancement

---

Tests/TechTalk.SpecFlow.IntegrationTests/TechTalk.SpecFlow.IntegrationTests.csproj
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj

The error was occurred when solution path contains a space character. I
escaped xcopy parameters with double quotes and error has gone.
https://github.com/techtalk/SpecFlow/commit/31959da8e82368f599de17c9770e0b1600326659#commitcomment-17040890

Fix a problem "xcopy ... exited with code 4" in post build action.

---

Tests/GeneratorTests/Data/sampleCsProjectfile.csproj
Tests/GeneratorTests/MsBuildProjectReaderTests.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/MsTestTestExecutionDriver.cs

These changes *de facto* force people to use VS2015 when developing SpecFlow. Is that acceptable?
You can of course still use SpecFlow for BDD in all supported Visual Studio editions, not only VS2015.

Make tests run on vs2015 only machine

---

Generator/UnitTestProvider/XUnitTestGeneratorProvider.cs
Tests/GeneratorTests/XUnitTestGeenratorProviderTests.cs

We use the `DisplayName` argument of the `Fact` attribute to specify a friendly test name to appear in the various reports and tools (e.g. in the VS Test Explorer).
**Warning:** This is a tentative (read: quick & dirty) patch, I'd be happy to take pointers on how to do this better or obviously let you do it better.
**Warning:** I have been unable to test this properly, I'd be grateful for some information on how to generate a build that I can use (ideally an alternate set of nuget packages). I essentially based a unit test off of existing ones to get some confirmation, I didn't dive deep into the project.

xUnit: Support friendly test name

---

Runtime/Bindings/StepArgumentTypeConverter.cs
Tests/RuntimeTests/StepArgumentTypeConverterTest.cs

Make sure StepArgumentTypeConverter and EnumValueRetriever (for tables) parse Enums the same way (both now remove whitespaces from string input).

Parse Enums consistently for step arguments and tables

---

TechTalk.SpecFlow/Tracing/CodeFormattingExtensions.cs
Tests/TechTalk.SpecFlow.GeneratorTests/GeneratorTests.csproj
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorTest.cs

This fix is for issue 300. I simply remove any quotes (double or single) in the name before it is processed. This also applies to step name.
Also added a test to verify the change.

Fixed generation of test name when apostrophe in scenario name. (Issue 300)

---

TechTalk.SpecFlow.Generator/UnitTestProvider/MsTestGeneratorProvider.cs
Tests/TechTalk.SpecFlow.GeneratorTests/MsTestGeneratorProviderTests.cs

Fix for issue #333 Generated code fails to compile if there is a name
collision between a namespace and a class

Add global namespace alais to FeatureSetup call

---

TechTalk.SpecFlow/Assist/TableDiffExceptionBuilder.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/TableDiffExceptionBuilderTests.cs
changelog.txt

Before this change, table differences against enumerables would look something like this:
```
| Doubles         |
| System.Double[] |
```
With this change, they will now look like this:
```
| Doubles |
| 1,2,3   |
```

List all items from an enumerable in a table

---

TechTalk.SpecFlow.Generator/UnitTestProvider/NUnitTestGeneratorProvider.cs
Tests/TechTalk.SpecFlow.Specs/Features/TaggedExamples.feature

Seanario Outline examples tags do not appear in ScenarioContext.ScenarioInfo.Tags - Fix issue 718

---

TechTalk.SpecFlow/Infrastructure/ContextManager.cs
TechTalk.SpecFlow/Infrastructure/IContextManager.cs
TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/ScenarioStepContextTests.cs

PR #626 tracks the current step block by maintaining a recursion nesting counter. This relies on the proper calling of the step context initialization / cleanup, otherwise the counter goes off.
In case of an error in the before/after step block hook, the cleanup is not called, so the "current step block" remains as it was even for further scenarios.
This PR fixes this by moving the clanup call to the right level. Also fixing a small issue, that the afterstep hook is called even if the step was undefined.

Fix error caused by the Before/AfterStepBlock hook error handling and PR 626

---

Tests/TechTalk.SpecFlow.RuntimeTests/ScenarioStepContextTests.cs

While doing my test refactoring PR a while back, I forgot to add the test attribute to three methods. I added those, and then noticed that in one scenario I had forgotten to add the essential cleanup call.

[Please Review and Merge] Add Test Attributes and one line of missing code

---

TechTalk.SpecFlow/Assist/TableExtensionMethods.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/TableHelperExtensionMethods/CreateSetHelperMethodTests_WithFuncAndTableRowArgument.cs
Tests/TechTalk.SpecFlow.RuntimeTests/RuntimeTests.csproj

I created an oveload of the CreateSet extension method that returns the corresponding TableRow as an argument. The overload can be helpfull, if you want to set constructor parameters based on table content.
I am not sure if returning the TableRow is the best idea, since you have to parse strings manually. Maybe you have a better idea.
Any suggestions are highly welcome.

Create set overload with table row in callback

---

TechTalk.SpecFlow/Bindings/StepDefinitionRegexCalculator.cs
Tests/TechTalk.SpecFlow.GeneratorTests/GeneratorTests.csproj
Tests/TechTalk.SpecFlow.GeneratorTests/packages.config
Tests/TechTalk.SpecFlow.IntegrationTests/TechTalk.SpecFlow.IntegrationTests.csproj
Tests/TechTalk.SpecFlow.IntegrationTests/packages.config
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/StepDefinitionRegexCalculatorTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/RuntimeTests.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/packages.config
Tests/TechTalk.SpecFlow.Specs/Features/StepDefinitionsWithoutRegex.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/ExecutionResultSteps.cs
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
Tests/TechTalk.SpecFlow.Specs/packages.config
changelog.txt

Fix various issues related to step definitions without regex (underscore, pascal case naming).
Added unit tests, removed "tests" from specs
Also fixes #715 #301

Regexless stepdef fixes

---

.gitignore
GitExtensions.settings

add repository shared gitextensions settings file with configuration for
- github links
- github issues
- appveyor build status
Appveyor support for gitextensions is comming in a version after v2.49 but can be used today with a private build of gitextensions master branch.

Add GitExtensions configuration file

---

TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/XUnitTestGeneratorProvider.cs
Tests/TechTalk.SpecFlow.GeneratorTests/XUnit2TestGeneratorProviderTests.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/XUnitTestExecutionDriver.cs
Tests/TechTalk.SpecFlow.Specs/Features/XUnit2Provider.feature

Merged PR #788 and #689 to fix #575. Added unit tests to XUnit2TestGeneratorProviderTests.cs and scenarios to XUnit2Provider.feature as requested in comments in the earlier pull requests.

Adds support for xUnit2 ITestOutputHelper #575

---

TechTalk.SpecFlow.Generator/Interfaces/FeatureFileInput.cs
TechTalk.SpecFlow.Generator/Interfaces/GenerationSettings.cs
TechTalk.SpecFlow.Generator/Interfaces/ITestGenerator.cs
TechTalk.SpecFlow.Generator/Interfaces/ITestGeneratorFactory.cs
TechTalk.SpecFlow.Generator/Interfaces/ProjectPlatformSettings.cs
TechTalk.SpecFlow.Generator/Interfaces/ProjectSettings.cs
TechTalk.SpecFlow.Generator/Interfaces/SpecFlowConfigurationHolder.cs
TechTalk.SpecFlow.Generator/Interfaces/TestGenerationError.cs
TechTalk.SpecFlow.Generator/Interfaces/TestGeneratorFactoryAttribute.cs
TechTalk.SpecFlow.Generator/Interfaces/TestGeneratorResult.cs
TechTalk.SpecFlow/Configuration/SpecFlowConfiguration.cs
Tests/TechTalk.SpecFlow.GeneratorTests/FeatureGeneratorRegistryTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/GeneratorContainerBuilderTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/IgnoredTestGeneratorTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/NUnit3GeneratorProviderTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorFactoryTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/UnitTestFeatureGeneratorTests.cs

During the work on PR https://github.com/techtalk/SpecFlow/pull/690 a refactoring changed https://github.com/techtalk/SpecFlow/blob/master/TechTalk.SpecFlow.Generator/Interfaces/SpecFlowConfigurationHolder.cs.
But this class is used in the Visual Studio Extension as parameter when the code generation is triggered (https://github.com/techtalk/SpecFlow.VisualStudio/blob/master/IdeIntegration/Generator/RemoteAppDomainTestGeneratorFactory.cs#L186).
As the two classes were different, the serialization could not deserialize the _content field.
This PR fixes that, with renaming the field back to _xmlString and adjusting the ConfigSource enum to have AppConfig as default value.

Fix generation from visual studio

---

TechTalk.SpecFlow.Generator/Project/MsBuildProjectReader.cs

~~use FileStream constructor which grants ReadWrite to other processes~~
Use another FileStream constructor, to be able to also read _readonly_ files.
See https://msdn.microsoft.com/en-us/library/47ek66wy(v=vs.110).aspx#Anchor_2
https://github.com/techtalk/SpecFlow/issues/904

use FileStream constructor which grants ReadWrite to other processes.

---

TechTalk.SpecFlow.Generator/UnitTestProvider/MsTestGeneratorProvider.cs
Tests/TechTalk.SpecFlow.Specs/Features/MsTestProvider.feature

Access MSTest's TestContext property via ScenarioContext

---

TechTalk.SpecFlow.Generator/UnitTestProvider/MsTest2010GeneratorProvider.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/InputProjectDriver.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/MsBuild/ProjectGenerator.cs
Tests/TechTalk.SpecFlow.Specs/Features/MsTestProvider.feature

[DeploymentItem] has an option to provide output directory, so either file or a complete source dir will be copied to new output dir:
[DeploymentItem("test1.xml")] //file available in root
[DeploymentItem("test2.xml", "Data")] //file available in Data dir (Data\test2.xml)
[DeploymentItem("Resources\\test3.xml")] //file available in  root
[DeploymentItem("Resources\\test4.xml", "Data")] //file available in Data dir (Data\test4.xml)
[DeploymentItem("Resources\\", "Data")] //all files available in Data dir (Data\*)
Current solution will preserve the current functionallity, output directory is an optional parameter. Changes needed to support this feature:
- MsTest2010GeneratorProvider.cs - understand @msbuild:deploymentitem:FileToDeploy:OutputDir syntax
- InputProjectDriver.cs - files can be …

@MsBuild [DeploymentItem] - added option to provide output directory

---

TechTalk.SpecFlow.Reporting/XsltHelper.cs
changelog.txt

Added support for custom XSLT files to contain the <msxsl:script> tag for more complex processing. In my case I'm flattening debug images into base64 encoded images in the report for a single file download from the CD server.

Allowed custom XSLT transforms to contain scripts.

---

TechTalk.SpecFlow.Reporting/Common/Common.xslt

Fixes #915 
The issue is caused by the double encoding of the `<` signs in XSLT in the generated the for loops, e.g:
```
for (colIndex = 0; colIndex &lt; header.length; colIndex++)
columnWidths[colIndex] = header[colIndex].innerHTML.length;
```
However I'm not sure that we need to keep this copy feature at all: see #957

Fixing copy link in step definition report

---

.gitignore
Installer/NuGetPackages/SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/Assist/TEHelpers.cs
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
TechTalk.SpecFlow/packages.config
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/CreateInstanceHelperMethodTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/TableHelperExtensionMethods/CreateSetHelperMethodTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/RuntimeTests.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/packages.config
appveyor.yml

This is a work in progress to support tuples on createinstance #950

[WIP] Experimental support for tuples

---

TechTalk.SpecFlow.Parser/SpecFlowGherkinParser.cs
Tests/TechTalk.SpecFlow.GeneratorTests/GeneratorTests.csproj
Tests/TechTalk.SpecFlow.GeneratorTests/ScenarioOutlineParserTests.cs
Tests/TechTalk.SpecFlow.Specs/Features/Parser/ParsingErrors.feature
changelog.txt

This is related to #792 (Better error message for Scenario Outlines without arguments)
Now a SemanticParserException will be thrown when Examples are missing from a Scenario Outline. The exception will point to the Outline with missing examples. Multiple Outlines without Examples are also handled.

Parsing exception on missing examples

---

TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/XUnitTestGeneratorProvider.cs
Tests/TechTalk.SpecFlow.Specs/Features/XUnit2Provider.feature
Tests/TechTalk.SpecFlow.Specs/Features/XUnitProvider.feature

Related to  #956. Using FinalizeTestClass method of XUnitTestGeneratorProvider to mark all Scenarios and Outlines as ignored when a Feature is tagged with @Ignore.
Not sure it this is the best/only way.

PoC for xUnit handling of @Ignore tag on a feature

---

TechTalk.SpecFlow/Assist/Attributes/TableAliasesAttribute.cs
TechTalk.SpecFlow/Assist/TEHelpers.cs
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/CreateInstanceHelperMethodTests.cs
changelog.txt

Provides the ability to add an attribute to your target class indicating aliases that may be used for the properties or fields in specflow feature tables.
The aliases are Regex strings that are used by the `CreateInstance` and `CreateInstances` table extension methods to map table entries to the fields on the mapped to class.
For usage examples, see the `CreateInstanceHelperMethodTests` specifically the `AliasedClass` which demonstates how a class can be decorated.

Add the ability to add aliases to target class properties

---

.gitignore
Installer/NuGetPackages/.build/build.targets
Installer/NuGetPackages/NuGetPackages.csproj
Installer/NuGetPackages/SpecFlow.Tools.MsBuild.Generation/SpecFlow.Tools.MsBuild.Generation.nuspec
Installer/NuGetPackages/SpecFlow/build/SpecFlow.targets
TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.props
TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.targets
TechTalk.SpecFlow.Tools/TechTalk.SpecFlow.Tools.csproj
Tests/TechTalk.SpecFlow.IntegrationTests/TechTalk.SpecFlow.IntegrationTests.csproj
Tests/TechTalk.SpecFlow.Specs/Drivers/Templates/TestProjectFile.csproj
Tests/TechTalk.SpecFlow.Specs/Drivers/Templates/TestProjectFile.fsproj
Tests/TechTalk.SpecFlow.Specs/Drivers/Templates/TestProjectFile.vbproj
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj

This PR adds the NuGet package SpecFlow.Tools.MsBuild.Generation and resolves #934 
Additionally it changes the SpecFlow package, so that this imports the MSBuild tasks always.
This helps this package and other packages, that depend on the MSBuild tasks, because you don't need anymore a version number in the import.

Add SpecFlow.Tools.MsBuild.Generation package

---

TechTalk.SpecFlow/Bindings/Reflection/BindingType.cs
TechTalk.SpecFlow/Bindings/Reflection/IBindingType.cs
TechTalk.SpecFlow/Bindings/Reflection/RuntimeBindingType.cs
TechTalk.SpecFlow/ErrorHandling/ErrorProvider.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/StepDefinitionRegexCalculatorTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/ErrorProviderTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/StepDefinitionMatchServiceTest.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/RuntimeTests.csproj
changelog.txt

Closes https://github.com/techtalk/SpecFlow/issues/994
- Updated ErrorProvider.GetMethodText
- Added unit tests for ErrorProvider

Display full method name in error messages

---

TechTalk.SpecFlow.Generator/Plugins/GeneratorPluginLocator.cs
changelog.txt

having the tools order as first makes problems with plugins, that ships a console program with reference to TechTalk.SpecFlow.dll
it could happen, that the wrong TechTalk.SpecFlow.dll is loaded

Adjust Plugin Folder Search Order

---

TechTalk.SpecFlow.Generator/UnitTestFeatureGenerator.cs
TechTalk.SpecFlow/ScenarioInfo.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestThreadContextTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/ScenarioContext_BindingInstancesTest.cs
Tests/TechTalk.SpecFlow.RuntimeTests/ScenarioStepContextTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/StepExecutionTestsBase.cs
Tests/TechTalk.SpecFlow.RuntimeTests/StronglyTypedContextAcessorTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/TestObjectFactories.cs
Tests/TechTalk.SpecFlow.RuntimeTests/TestRunnerManagerRunnerCreationTests.cs
Tests/TechTalk.SpecFlow.Specs/Features/Description.feature
Tests/TechTalk.SpecFlow.Specs/Features/Parser/DescriptionParser.feature
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
changelog.txt

Expose ScenarioInfo.Description parameter to get from context

---

Installer/NuGetPackages/NuGetPackages.csproj

This is required in case custom location for Nuget packages specified
using NUGET_PACKAGES environment variable. It is prevent me from building locally

Use standard MSBuld variable for getting location of Nuget packages

---

TechTalk.SpecFlow.Rpc.Tests/Client/ExtractMethodInfoTests.cs
TechTalk.SpecFlow.Rpc/Client/ExtractMethodInfo.cs

This change to allow test in `TechTalk.SpecFlow.Rpc.Tests.SameProcess.MultipleCalls()` use expression `"FeatureFilePath" + i`. Related to #1121
I now have feeling that when such code should be applied to all cases, to account for all possible way to pass parameters.

Allow use binary expression in method call

---

TechTalk.SpecFlow.Generator/DefaultDependencyProvider.cs
TechTalk.SpecFlow.Generator/TestGenerator.cs
TechTalk.SpecFlow.Parser/IGherkinParser.cs
TechTalk.SpecFlow.Parser/IGherkinParserFactory.cs
TechTalk.SpecFlow.Parser/SpecFlowGherkinParser.cs
TechTalk.SpecFlow.Parser/SpecFlowGherkinParserFactory.cs
TechTalk.SpecFlow.Parser/TechTalk.SpecFlow.Parser.csproj
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorTestsBase.cs
changelog.txt

`SpecFlowGherkinParser` now implements `IGherkinParser`. `IGherkinParserFactory` and it's default implementation `SpecFlowGherkinParserFactory` are added to create a default parser.
This resolves #1104

Support plugable GherkinParser

---

TechTalk.SpecFlow/Bindings/BindingMatch.cs
TechTalk.SpecFlow/Bindings/BindingObsoletion.cs
TechTalk.SpecFlow/Configuration/AppConfig/AppConfigConfigurationLoader.cs
TechTalk.SpecFlow/Configuration/AppConfig/RuntimeConfigElement.cs
TechTalk.SpecFlow/Configuration/ConfigDefaults.cs
TechTalk.SpecFlow/Configuration/ConfigurationLoader.cs
TechTalk.SpecFlow/Configuration/JsonConfig/JsonConfigurationLoader.cs
TechTalk.SpecFlow/Configuration/JsonConfig/RuntimeElement.cs
TechTalk.SpecFlow/Configuration/ObsoleteBehavior.cs
TechTalk.SpecFlow/Configuration/SpecFlowConfiguration.cs
TechTalk.SpecFlow/ErrorHandling/ErrorProvider.cs
TechTalk.SpecFlow/Infrastructure/DefaultDependencyProvider.cs
TechTalk.SpecFlow/Infrastructure/IObsoleteStepHandler.cs
TechTalk.SpecFlow/Infrastructure/ObsoleteStepHandler.cs
TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/TechTalk.SpecFlow.Specs/Features/ObsoleteSteps.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/SpecFlowConfigurationSteps.cs
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
changelog.txt

This fixes #893 (or should). `ObsoleteAttribute` is used and the behavior is configurable, defaulted to warn, a non-breaking one.
I'm yet to update changelog and docs, but first I'd like a review.

Support for marking Steps as Obsolete

---

TechTalk.SpecFlow/Assist/ValueRetrievers/GuidValueRetriever.cs
changelog.txt

`GuidValueRetriever.cs` now compares a Guid with a string using case insensitivity to prevent throwing unnecessary exceptions.

Comparing Guid with string using case insensitivity to prevent throwing unnecessary exceptions

---

TechTalk.SpecFlow/Assist/TEHelpers.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/SetComparisonExtensionMethods_ThrowTests.cs
changelog.txt

```gherkin
Given the English word 'name' is 'név' in Hungarian
And I prefer to have a scenario containing correctly spelled column headers like this
```
| Név       |
| dr. X. Y. |
```
And I don't allow local characters in the source code
When I try to compare the table with this object
```
public class C
{
public string Nev { get; set; } 
}
```
Then the table and the object can be successfully compared
```

SpecFlow.Assist: apply ToIdentifier transform to column headers when comparing tables

---

TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.props
TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.targets
changelog.txt

Several improvements for current MSBuild based code-behind files generation  
- Try to fix incremental build issue inside visual studio 2017 if feature file changed outside of visual studio
- typically you'll see the message 'target skipped because of no input files changed'
- this fix should also work more reliable if using MSBuild from command line
- this fix should also improve compatibility with new sdk based MSBuild projects
- add experimental support for deleting code-behind files on clean or rebuild
- to use code-behind file deletion you'll have to set the MSBuild property 'SpecFlow_DeleteCodeBehindFilesOnCleanRebuild' to 'true' inside your csproj or using on of the directory or solution extension points in MSBuild https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your …

MSBuild generation: incremental build and clean rebuild improvements

---

TechTalk.SpecFlow.Generator/UnitTestFeatureGenerator.cs
changelog.txt

This fix was created as a result of using generator plugin: for ordinary tests custom code was generated before test body, for outline tests it was generated after test body.

Fixed test body generation order for outline tests

---

TechTalk.SpecFlow.Generator/TestClassGenerationContext.cs
TechTalk.SpecFlow.Generator/UnitTestFeatureGenerator.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/MsTestGeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/NUnitTestGeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/XUnitTestGeneratorProvider.cs
TechTalk.SpecFlow/ITestRunner.cs
TechTalk.SpecFlow/Infrastructure/ITestExecutionEngine.cs
TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
TechTalk.SpecFlow/TestRunner.cs
Tests/TechTalk.SpecFlow.GeneratorTests/DecoratorRegistryTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/MsTestGeneratorProviderTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/XUnit2TestGeneratorProviderTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/XUnitTestGeneratorProviderTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/TestRunnerManagerRunnerCreationTests.cs
Tests/TechTalk.SpecFlow.Specs/Features/MsTestProvider.feature
Tests/TechTalk.SpecFlow.Specs/Features/NUnitProvider.feature
Tests/TechTalk.SpecFlow.Specs/Features/XUnit2Provider.feature
changelog.txt

Fix XUnit ITestOutputhelper and MSTest TestContext container registrations so that they are available in BeforeScenario hooks.

Fix for issue 936 - make sure container registrations are available in BeforeScenario hooks

---

TechTalk.SpecFlow/Assist/SetComparer.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/SetComparisonExtensionMethods_MessageTests.cs

Currently, if there are fewer returned results than the table has rows, using order insensitive comparison displays the absent rows, but order sensitive comparison does not. This adds a test for the latter case and fixes the implementation.
I also cleaned up the implementation slightly, hopefully without changing the behaviour: it now calculates missing items once, instead of three times, and no longer considers "there are results but should be none" separately to "there are more results than expected", as the former is a subcase of the latter.

Order sensitive comparison should display missing rows if there are more expected rows in the table than were returned

---

.gitignore
Installer/NuGetPackages/.build/build.targets
Installer/NuGetPackages/NuGetPackages.csproj
TechTalk.SpecFlow.Generator/Project/MsBuildProjectReader.cs
TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.props
TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.targets
TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.tasks
TechTalk.SpecFlow.sln
Tests/TechTalk.SpecFlow.IntegrationTests/App.config
Tests/TechTalk.SpecFlow.IntegrationTests/TechTalk.SpecFlow.IntegrationTests.csproj
Tests/TechTalk.SpecFlow.IntegrationTests/packages.config
Tests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests/App.config
Tests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests/Bindings/DoNothingBinding.cs
Tests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests/CodeBehindFileGenerationTests.cs
Tests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests/Features/dummy.feature
Tests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests.csproj
Tests/TechTalk.SpecFlow.Specs/App.config
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
Tests/TechTalk.SpecFlow.Specs/packages.config
changelog.txt

This pull request extends support for net.sdk project system when MSBuild Generation is used
- enables usage of net.sdk project type system when **targeting desktop framework => not .net core support**
- globbing support for nesting codebehind files under feature files
- fixed handling of added and removed codebehind files after regeneration
- added warning if codebehind files without corresponding feature file is present (only for net.sdk project system enabled by default)
As this integration is experimental, you have to enable it via the following MSBuild property
- inside your csproj
- or using on of the directory or solution extension points in MSBuild https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build
``` 
<PropertyGroup> …
```

MsBuild Extended support for net.sdk project type system (targeting desktop framework, not core)

---

TechTalk.SpecFlow/Assist/Service.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ServiceTests.cs
changelog.txt

Currently, replacing only the default value comparer while keeping all others the same involves rather a lot of code:
var existingComparers = Service.Instance.ValueComparers.ToList();
foreach (var existingComparer in existingComparers)
{
Service.Instance.UnregisterValueComparer(existingComparer);
}
Service.Instance.RegisterValueComparer(new NullConversionDefaultValueComparer());
foreach (var existingComparer in existingComparers.Where(x => !(x is DefaultValueComparer)))
{
Service.Instance.RegisterValueComparer(existingComparer);
}
This change separates the handling of default and non-default value comparers, and stops it splitting on the type.

Separate addition of default and non-default value comparers.

---

TechTalk.SpecFlow/Assist/InstanceComparisonExtensionMethods.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/InstanceComparisonExtensionMethodsTests.cs
changelog.txt

Fixes #1253 
The ComparisonException indicates which `IValueComparer` was used for each difference, to help determine why two objects are seemingly different.
Before:
```
The following fields did not match:
StringProperty: Expected <Howard Roark>, Actual <Peter Keating>
IntProperty: Expected <1>, Actual <2>
```
After:
```
The following fields did not match:
StringProperty: Expected <Howard Roark>, Actual <Peter Keating>, Using 'TechTalk.SpecFlow.Assist.ValueComparers.DefaultValueComparer'
IntProperty: Expected <1>, Actual <2>, Using 'TechTalk.SpecFlow.Assist.ValueComparers.DefaultValueComparer'
```

ComparisonException indicates which value comparer was used for each difference

---

TechTalk.SpecFlow/Assist/TEHelpers.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/TableHelperExtensionMethods/CreateInstanceHelperMethodTests.cs
changelog.txt

CreateInstance can currently use a non-default constructor, but it checks for parameters case-sensitively to exactly match the names of the properties. If a PascalCased property is set using a camelCased parameter, it is not found.
This change adds the ability to use a constructor where the parameters match the property names case-insensitively.

Use case-insensitive parameter name checking when calling CreateInstance

---

TechTalk.SpecFlow/Assist/ValueRetrievers/BoolValueRetriever.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/BoolValueRetrieverTests.cs
changelog.txt

This is the PR for #1216.  
As discussed there, this change allows allows the `BoolValueRetriever` to work with `1` and `0`s.
Apologies for the delay in getting this ready - it's been a busy summer!

The `BoolValueRetriever` can now work with `1` and `0`s

---

TechTalk.SpecFlow/Assist/Service.cs
TechTalk.SpecFlow/Assist/ServiceComponentList.cs
TechTalk.SpecFlow/Assist/SpecFlowDefaultValueComparerList.cs
TechTalk.SpecFlow/Assist/SpecFlowDefaultValueRetrieverList.cs
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ServiceComponentListTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/RuntimeTests.csproj
changelog.txt

Fixes #1218
I think there is too much similarity in comparer and retriever handling in the Assist service, so I propose they could be merged into one with a small API change:
Before:
```
Service.Instance.RegisterValueComparer(___)
```
After:
```
Service.Instance.ValueComparers.Register(___)
```
Additions:
```
Service.Instance.ValueComparers.Register<MyClass>()
Service.Instance.ValueComparers.Unregister<MyClass>()
Service.Instance.ValueComparers.Replace(oldObj, newObj)
Service.Instance.ValueComparers.Replace<OldClass, NewClass>()
```
Pros:
- simplifies future maintenance
Cons:
- breaking change
- RegisterDefault only applied to comparers in the past (and it's weird to add more "default"s to a single list but I did not change this behavior)

Improve value retriever/comparer registration

---

TechTalk.SpecFlow/Assist/RowExtensionMethods.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/RowExtensionMethodTests.cs
changelog.txt

Enchancement to retrieve Enum field value from table row.
Before in test we should do:
```
var sex = (Sex) Enum.Parse(typeof(Sex), row["RowColName"])
```
Now in test we can do:
```
var sex = row.GetEnumValue<Sex>("RowColName");
```

Add utility to get enum field value from TableRow

---

TechTalk.SpecFlow/Assist/Service.cs
TechTalk.SpecFlow/Assist/ServiceComponentList.cs
TechTalk.SpecFlow/Assist/SpecFlowDefaultValueComparerList.cs
TechTalk.SpecFlow/Assist/ValueHolder.cs
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ServiceComponentListTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ServiceTests.cs
changelog.txt

Following on from #1257, this pull request puts in a slightly more sensible contract of only having one default at any time, and takes advantage of the newly added generics.
I've deleted the old implementation as it was never part of a released version, so it didn't seem to make much sense to include it (same for the obsoleted method). I can add it back if you'd like.
I'm not completely sold on the "SetDefault" naming.
It's a breaking change for the existing functionality, but not since the last release.

Replace "RegisterDefault" ValueX implementation and use new generics

---

TechTalk.SpecFlow/TestRunnerManager.cs
TechTalk.SpecFlow/Tracing/TestTracer.cs
Tests/TechTalk.SpecFlow.IntegrationTests/Features/Tracing.feature
Tests/TechTalk.SpecFlow.RuntimeTests/TestRunnerManagerRunnerCreationTests.cs
changelog.txt

Fixes #1293
extend `TestTracer.TraceError`
- check if caught exception is a `ReflectionTypeLoadException`
- append the loader exceptions to SpecFlow output

append loader exceptions to error output

---

TechTalk.SpecFlow/Assist/TEHelpers.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/TableHelperExtensionMethods/CreateInstanceHelperMethodTests.cs
changelog.txt

When CreateInstance uses a non-default constructor, it passes in null to all parameters not set by the table. This change modifies that behaviour to use a default if one exists.
One use-case of ours this supports is having a model object with a constructor where all the parameters have defaults (for use in non-SpecFlow component tests, for example): SpecFlow now creates the object similarly to a constructor call that passes in the table parameters using keywords.
This is technically breaking in that previously null would be passed for all non-table parameters, and now the default is used if it exists.

Use default constructor parameters when calling CreateInstance

---

TechTalk.SpecFlow/Assist/TableDiffExceptionBuilder.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/SetComparisonExtensionMethods_MessageTests.cs

Display differences with milliseconds and ticks between two DateTime fields in a ComparisonException.

---

TechTalk.SpecFlow/Assist/RowExtensionMethods.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/RowExtensionMethodTests.cs
changelog.txt

Extended the RowExtensionMethods class with two CreateInstance<T> methods for a TableRow.

Add CreateInstance<T> support to a TableRow

---

TechTalk.SpecFlow/Assist/ValueRetrievers/NullValueRetriever.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/NullValueRetrieverTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/ValueRetrieverTestsUtils.cs
changelog.txt

A NullValueRetriever implemented that can be used to explicitly set null values according to #1389. The retriever is intentionally not added as a default retriever. The target project can add this to default retrievers and specify the null text if the project needs that.
If this will be merged in, the following change to documentation is needed (sorry, I don know how to include wiki change in a pull request). I can update the docs if you decide to merge.
In the end of [SpecFlow-Assist-Helpers](https://github.com/techtalk/SpecFlow/wiki/SpecFlow-Assist-Helpers)
````
By default, non-specified (empty string) values are considered:
* an empty string for `String` and `System.Uri` values
* a null value for `Nullable<>` primitive types
* an error for non-nullable primitive types
Explicit …
```

NullValueRetriever implemented

---

Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/RuntimePlugin.cs
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/XUnitTraceListener.cs

When tests are executed with xUnit (e.g. with VS Test Explorer), the standard SpecFlow trace information (running steps, etc.) is not included in the output.
The issue is caused by the registration of the XUnitTraceListener, that was registered to the Scenario container, although SpecFlow reads it out from the Test Thread Container. The plugin is changed now to register it to the right container and inside the method it checks if the `ITestOutputHelper` is available and if yes, it forwards the message there. 
Tested manually.
- [x ] Bug fix (non-breaking change which fixes an issue).

Fix XUnit output (SpecFlow trace information were not displayed in Test Explorer)

---

TechTalk.SpecFlow/TestRunnerManager.cs
Tests/TechTalk.SpecFlow.RuntimeTests/RuntimeBindingRegistryBuilderTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/TestRunnerManagerStaticApiTest.cs

In order to fix #1348 in a way as @SabotageAndi suggested, we need an easy way to ensure that the AfterTestRun hooks fired even before AppDomain unload. 
This PR exposes an `OnTestRunEnd` method on the static API of `TestRunnerManager` to support this. The `OnTestRunEnd` method is safe to call multiple times (or call it before domain unload), it will fire the events only once.

Preparation to fix #1348: Expose TestRunnerManager.OnTestRunEnd to be able to call it from plugins

---

TechTalk.SpecFlow/Bindings/AsyncHelpers.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/AsyncHelperTests.cs

Fixes #1509
Always reset the SynchronizationContext at the end of AsyncHelpers.RunAsync.
Repeated the tests for RunSync against the RunSync<T> overload.

SynchronizationContext is not reset if async method throws an exception

---

TechTalk.SpecFlow/BindingSkeletons/DefaultSkeletonTemplateProvider.cs
TechTalk.SpecFlow/ErrorHandling/BindingException.cs
TechTalk.SpecFlow/ErrorHandling/MissingStepDefinitionException.cs
TechTalk.SpecFlow/ErrorHandling/PendingStepException.cs
TechTalk.SpecFlow/ErrorHandling/SpecFlowException.cs
TechTalk.SpecFlow/FeatureContext.cs
TechTalk.SpecFlow/ScenarioContext.cs
TechTalk.SpecFlow/TestRunnerManager.cs

Silverlight is dead. Remove `#if SILVERLIGHT` from code.
- [] I've added tests for my code.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have added an entry to the changelog

Remove `#if SILVERLIGHT` from code for issue #1502

---

Tests/TechTalk.SpecFlow.Specs/Features/UnitTestProviderSpecific/XUnit/XUnit2Provider.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/FeatureFileSteps.cs

Support of xunit collection , introduced in https://github.com/techtalk/SpecFlow/pull/1380, doesn't have real testing. It just compiles and that's all. Now it's added for two cases:
1) Usage of collection tag in feature file actually makes xunit initialize collections and related TFixture
2) Usage of collection tag in feature adds test category (Traits in xunit terms). Actually, it's not required by xunit, but as I see any tag should be treated as category so let's test it too. 
Also, test output compare is added too.
- [x ] Bug fix (non-breaking change which fixes an issue).
- [x ] I've added tests for my code.

Proper tests for xunit2 collection support

---

SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.targets
changelog.txt

Remove necessity of adding the "AfterUpdateFeatureFilesInProject" target when using the classic project format and MSBuild generation

---

TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/XUnitTestGeneratorProvider.cs

Hi,
This PR updates the `XUnitTestGeneratorProvider` so that the `internal const`'s are now `protected internal`, so that anyone extending this class can make use of them. It also changes the `SetTestMethodCategories` method to be `virtual`, as I require this for a project I'm working on.  
I am currently working around this by having a copy of this file in my own project, but would rather these changes were upstream so I'm not duplicating your code :)
I don't know if any of the above are required, if so please let me know & I'll happily do them :)

Make XUnitTestGeneratorProvider consts & method protected & virtual

---

TechTalk.SpecFlow/Infrastructure/ContainerBuilder.cs
TechTalk.SpecFlow/Plugins/IRuntimePluginLocator.cs
TechTalk.SpecFlow/Plugins/RuntimePluginLocator.cs
TechTalk.SpecFlow/TestRunnerManager.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/PluginTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestThreadContextTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/TestObjectFactories.cs
Tests/TechTalk.SpecFlow.RuntimeTests/TestRunnerManagerTest.cs

as on .NET Core the SpecFlow.dll is not in the output folder and current directory is set to the TestResults folder, we have to search for runtime plugins in the test assembly folder

RuntimePlugin Locator looks into TestAssembly folder

---

SpecFlow.Tools.MsBuild.Generation/GenerateFeatureFileCodeBehindTask.cs
TechTalk.SpecFlow.Generator/TestGenerator.cs
Tests/TechTalk.SpecFlow.GeneratorTests/MSBuildTask/GenerateFeatureFileCodeBehindTaskTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/MsBuildProjectReaderTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorBasicsTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorTestsBase.cs
changelog.txt

* Remove [Required] from build task RootNamespace
* Take folder paths into account when root namespace absent
* Add tests for previously supported and new scenarois
This fixes https://github.com/techtalk/SpecFlow/issues/1605
It also makes the behaviour in empty-root-namespace scenarios more consistent with when the root namespace is specified. Back when empty root namespaces worked (which they did if you used the custom tool to generate codebehind) the folder path to the class wasn't taken into account like it is in non-empty cases. You just ended up with the same default namespace for everything. With this change, files in subfolders go in namespaces based on that file structure, exactly like they do when the root namespace is non-empty, and exactly as happens when you ask VS to add a …

Empty root namespace

---

TechTalk.SpecFlow/Configuration/ConfigurationLoader.cs
Tests/TechTalk.SpecFlow.Specs/Features/Execution/Configuration.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/ConfigurationSteps.cs
changelog.txt

The GetSpecflowJsonFilePath method was looking for the specflow.json file in Environment.CurrentDirectory which may not be set to the same paths for all test frameworks. This was changed to AppDomain.CurrentDomain.BaseDirectory (the same directory as the project file).
I have also changed the assertions for the configuration tests to look for strings such as "Using specflow.json" in the compile results output instead of the test results output.

Fix1544 - Change search path for specflow.json and update configuration tests

---

SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.props

SpecFlow.Tools.MsBuild.Generation.props used a different casing to reference the Buildsystem folder than is present in the package. This seems like the smallest change to correct an out of the box failure utilising the MsBuild generation on linux. Is nobody using SpecFlow on linux or macOS at the moment? Anyway this fix isn't a code change and the casing of a path should have no effect on Windows users.

Correct props file path case

---

TechTalk.SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/TechTalk.SpecFlow.ExternalAnnotations.xml

- Allows ReSharper to know that code with Binding/Given/When/Then attributes is implicitly used
- Light up Regex editing for regex parameters
Implements #1639

Add ReSharper external annotations

---

TechTalk.SpecFlow/Bindings/StepArgumentTypeConverter.cs
Tests/TechTalk.SpecFlow.RuntimeTests/StepArgumentTypeConverterTest.cs
changelog.txt

I added support for TypeConverter attributes in an effort to support my scenario. I have type called VariableDouble that supports a type conversion from string via TypeConverterAttribute. It's different from a regular double in the sense that it supports notation for tolerance, such as "1.5 +/- 0.2", therefore it needs custom conversion from string. It can be used as follows:
```
// Class definition
[TypeConverter(typeof(VariableDoubleConverter))]
public class VariableDouble { }
// Usage
[Then(@"the value should be (.+)")]
public void TheValueShouldBe(VariableDouble expectedValue);
```

Added support for TypeConverter attributes.

---

TechTalk.SpecFlow.Generator/Generation/UnitTestMethodGenerator.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorTest.cs
changelog.txt

Adjust parameter names generation (#1694)

---

TechTalk.SpecFlow/Configuration/AppConfig/AppConfigConfigurationLoader.cs
TechTalk.SpecFlow/Configuration/AppConfig/ConfigurationSectionHandler.cs
TechTalk.SpecFlow/Configuration/AppConfig/CucumberMessageSinkElement.cs
TechTalk.SpecFlow/Configuration/AppConfig/CucumberMessagesElement.cs
TechTalk.SpecFlow/Configuration/AppConfig/CucumberMessagesSinkCollection.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Configuration/AppConfigTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/Sinks/ProtobufFileSinkOutputTests.cs
Tests/TechTalk.SpecFlow.Specs/Features/Configuration/Cucumber-Messages App.Config Configuration.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/SpecFlowConfigurationSteps.cs
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj

Add app.config configuration for Cucumber-Messages

---

TechTalk.SpecFlow/Bindings/Discovery/BindingSourceProcessor.cs
TechTalk.SpecFlow/Bindings/Reflection/BindingReflectionExtensions.cs
TechTalk.SpecFlow/Bindings/Reflection/IPolymorphicBindingType.cs
TechTalk.SpecFlow/Bindings/Reflection/RuntimeBindingType.cs
TechTalk.SpecFlow/Infrastructure/StepDefinitionMatchService.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/StepDefinitionMatchServiceTest.cs
Tests/TechTalk.SpecFlow.RuntimeTests/RuntimeBindingRegistryBuilderTests.cs
changelog.txt

This issue is related to #1745. Although it will not fix it but provides the necessary infrastructure for a good workaround.
SpecFlow finds step definitions if they are attributed with Given, When, Then or StepDefinition attributes only but not when a derived attribute is used. This might be a problem for non-English projects, where the attribute name might be misleading (e.g. `[Then("sollte etwas passieren")]` for step `Dann sollte etwas passieren`). 
This PR provides support for using derived attributes, so one can create a language-specific attribute, like 
```
public class DannAttribute : ThenAttribute
{
public DannAttribute(string regex) : base(regex, "de-DE") {}
}
```
Later we might provide these translated attributes as additional packages (at least for commonly used languages). …

Support discovering step definitions from attributes that are derived from Given,When,Then or StepDefinition attributes (related to #1745)

---

TechTalk.SpecFlow.Parser/SpecFlowFeature.cs
Tests/TechTalk.SpecFlow.Specs/Features/Parser/RuleSupport.feature
changelog.txt

Gherkin v6 introduced a new "Rule" keyword that can be used to group scenarios. This PR adds a basic support for this syntax element: SpecFlow will execute the scenarios also within Rule blocks in feature files (these scenarios were ignored in SpecFlow v3.0).

Gherkin v6 Rule keyword support

---

Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/MSTest.AssemblyHooks.cs
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/MSTest.AssemblyHooks.vb
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/SpecFlow.MsTest.targets
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/NUnit.AssemblyHooks.cs
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/NUnit.AssemblyHooks.vb
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/SpecFlow.NUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/SpecFlow.xUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/xUnit.AssemblyHooks.cs
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/xUnit.AssemblyHooks.vb
SpecFlow.Tools.MsBuild.Generation/ReplaceTokenInFileTask.cs
SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.targets
SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.tasks
TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
Tests/TechTalk.SpecFlow.GeneratorTests/UnitTestProvider/XUnit2TestGeneratorProviderTests.cs
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/CombinationFeatureGenerator.cs
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/CustomXUnitGeneratorProvider.cs
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/MultiFeatureGeneratorProvider.cs
Tests/TechTalk.SpecFlow.Specs/Features/MultipleSpecsProjects.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/MultipleSpecsProjectsSteps.cs

10864 multiple projects issue

---

TechTalk.SpecFlow.Parser/SpecFlowGherkinParser.cs
Tests/TechTalk.SpecFlow.GeneratorTests/ScenarioOutlineParserTests.cs
Tests/TechTalk.SpecFlow.Specs/Features/Execution/ScenarioOutlines.feature
changelog.txt

A scenario with an "Examples" block should be treated as a Scenario Outline according to Gherkin v6 according to https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md#6013---2018-09-25. This PR fixes this.

Gherkin6 Scenario with Examples should be treated as a Scenario Outline

---

Tests/TechTalk.SpecFlow.Specs/Support/Hooks.cs

Currently the XUnit stage fails with the error: "There is not enough space on the disk"
The PR improves the following things:
- the MSBuild verbosity level is reduced to minimal in the `VSTestExecutionDriver`
- the generated test projects are deleted after the scenario is succeed and not kept around until the end of the whole test run

Reduce the file system "load" in Azure Pipelines

---

.gitignore
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/SpecFlow.MSTest.nuspec
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin.csproj
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/MSTest.AssemblyHooks.template.cs
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/MSTest.AssemblyHooks.template.vb
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/SpecFlow.NUnit.nuspec
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin.csproj
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/NUnit.AssemblyHooks.template.cs
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/NUnit.AssemblyHooks.template.vb
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/SpecFlow.xUnit.nuspec
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin.csproj
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/xUnit.AssemblyHooks.template.cs
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/xUnit.AssemblyHooks.template.vb
Tests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests.csproj
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
changelog.txt

In order to prevent codeanalysis tools to generate warnings for AssemblyHooks, the [GeneratedCode] attribute was added.
Fixes #1789

Added GenerateCodeAttribute to AssemblyHooks

---

Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/SpecFlow.MsTest.targets
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/SpecFlow.NUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/SpecFlow.xUnit.targets

When IntermediateOutputPath is an absolute path simple concatenation results in a non functional path, but by using Path.Combine which takes absolute paths into consideration there is no problem.
Fixes #1892

Use Path.Combine to build GeneratedSpecFlowAssemblyHooksFile path

---

TechTalk.SpecFlow.Generator/Generation/UnitTestMethodGenerator.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/IUnitTestGeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/MsTestGeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/MsTestV2GeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/NUnit3TestGeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorBasicsTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorTestsBase.cs
Tests/TechTalk.SpecFlow.GeneratorTests/UnitTestProvider/NUnit3GeneratorProviderTests.cs
Tests/TechTalk.SpecFlow.Specs/Features/Execution/BasicExecution.feature
changelog.txt

Use TestCase with Name instead of Description Attribute for Nunit3 provider. Fix #1225

---

TechTalk.SpecFlow/Analytics/UserId/FileUserIdStore.cs

Use the built in `Environment.SpecialFolder.ApplicationData` to get the environment specific (Windows/Linux/Mac) `AppData` folder.

Fix Unix analytics

---

TechTalk.SpecFlow/Assist/InstanceCreationOptions.cs
TechTalk.SpecFlow/Assist/TEHelpers.cs
TechTalk.SpecFlow/Assist/TableExtensionMethods.cs
TechTalk.SpecFlow/ErrorHandling/ColumnCouldNotBeBoundException.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/CreateInstanceHelperMethodTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ExampleEntities/PersonWithMandatoryLastName.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/TableHelperExtensionMethods/CreateSetHelperMethodTests.cs
changelog.txt

with InstanceCreationOptions/VerifyAllColumnsBound 
examples:
```c#
var options = new InstanceCreationOptions { VerifyAllColumnsBound = true };
var persons = table.CreateSet<Person>(options);
```
```c#
var options = new InstanceCreationOptions { VerifyAllColumnsBound = true };
var person = table.CreateInstance<Person>(options);
```
- binary compatible
- forward compatible for more changes in the future
If you have prefer other names for the classes/options, let me know
fixes https://github.com/SpecFlowOSS/SpecFlow/issues/1943

Created VerifyAllColumnsBound check

---

Tests/TechTalk.SpecFlow.RuntimeTests/TraceListenerQueueTests.cs

List<T> is not threadsafe and replaced with ConcurrentBag<T>
fixes https://github.com/SpecFlowOSS/SpecFlow/issues/1771 
I'm not sure what is mandatory for this change. I don't think it should be in the changelog

Fix flaky test EnqueueMessage_nTimes_ShouldBeSynchronous

---

TechTalk.SpecFlow/BindingSkeletons/StepTextAnalyzer.cs
Tests/TechTalk.SpecFlow.RuntimeTests/BindingSkeletons/StepTextAnalyzerTests.cs
changelog.txt

Recognize dates when generating steps. Datetimes aren't supported *yet*
Supported formats:
The ones that will be successfully parsed by Datetime.TryParse and limited to the following separators: `/`, `-` and `.`
Examples:
- 2030-12-23
- 2030/12/23
- 23-12-2030
- 23.12.2030
Please give me a glue if I could some more tests on a higher level.  I'm not sure if I have covered all needed parts and how I could test the end result easily.
Added `CaptureWithContext` / `ParameterType` as there where clashes:
- `23.12.2030` was successfully parsed with `decimal.TryParse` (unwanted)
- `4.2`  was successfully parsed with `DateTime.TryParse` (unwanted)

Recognize dates when generating steps

---

TechTalk.SpecFlow.Generator/UnitTestProvider/NUnit3TestGeneratorProvider.cs
changelog.txt

Changes SetTestMethodCategories so that this method can be overridden by plugins. This is needed for NUnit Retry since they have to happen at the method level, not the class level.

Allow override of Set Test Method Categories to allow NUnit Retry plugin to be developed

---

TechTalk.SpecFlow/Attributes.cs
TechTalk.SpecFlow/Bindings/Discovery/BindingSourceProcessor.cs
TechTalk.SpecFlow/Bindings/Discovery/SpecFlowAttributesFilter.cs
Tests/TechTalk.SpecFlow.RuntimeTests/RuntimeBindingRegistryBuilderTests.cs
changelog.txt

These changes allow for creation and usage of custom stepdefinition attributes like:
```
public class GivenAndWhenAttribute : StepDefinitionBaseAttribute
{
public GivenAndWhenAttribute(string regex)
: base(regex, new[] { StepDefinitionType.Given, StepDefinitionType.When })
{
}
}
```
Closes #1932

Allow the use of custom subclasses of StepDefinitionBaseAttribute.

---

TechTalk.SpecFlow/BindingSkeletons/FileBasedSkeletonTemplateProvider.cs
TechTalk.SpecFlow/Infrastructure/ContextManager.cs
changelog.txt

This MR prevents these 2 multi-thread related errors that happen randomly when running tests in parallel:
```
TechTalk.SpecFlow.SpecFlowException : Invalid sftemplate file! Duplicate key: 'CSharp/StepDefinitionRegex'.
at TechTalk.SpecFlow.BindingSkeletons.FileBasedSkeletonTemplateProvider.EnsureInitialized()
```
```
System.NullReferenceException : Object reference not set to an instance of an object.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
at TechTalk.SpecFlow.Infrastructure.ContextManager.InitializeScenarioContext(ScenarioInfo scenarioInfo)
```

Fix parallel executions exceptions

---

TechTalk.SpecFlow/Assist/ValueRetrievers/EnumValueRetriever.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/SituationalTests/NullableEnumTests.cs
changelog.txt

supersedes https://github.com/SpecFlowOSS/SpecFlow/pull/822
fixes #404
@SabotageAndi thanks for the tests! :)

Fix enum retriever for nullable enums and empty value

---

SpecFlow.Tools.MsBuild.Generation/GenerateFeatureFileCodeBehindTaskContainerBuilder.cs
TechTalk.SpecFlow/Analytics/AnalyticsEventProvider.cs
TechTalk.SpecFlow/Analytics/AppInsights/AppInsightsEventTelemetry.cs
TechTalk.SpecFlow/Analytics/IAnalyticsEvent.cs
TechTalk.SpecFlow/Analytics/SpecFlowAnalyticsEventBase.cs
TechTalk.SpecFlow/Analytics/SpecFlowProjectCompilingEvent.cs
TechTalk.SpecFlow/Analytics/SpecFlowProjectRunningEvent.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Analytics/AnalyticsEventProviderTests.cs

Include the BuildServerName in the analytics events and extend the list of the detected build servers.

Extend the build server detection and reporting

---

TechTalk.SpecFlow/Assist/TEHelpers.cs
changelog.txt

Changed invalid property name chars RegEx from being a new
instance every call to a single static compiled RegEx

RegEx performance fix in TEHelpers

---

TechTalk.SpecFlow.Generator/Generation/GeneratorConstants.cs
TechTalk.SpecFlow.Generator/Generation/UnitTestMethodGenerator.cs
TechTalk.SpecFlow/ScenarioInfo.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/CucumberMessageSenderTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/PickleIdStoreTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/TestResultFactoryTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestThreadContextTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/ScenarioContext_BindingInstancesTest.cs
Tests/TechTalk.SpecFlow.RuntimeTests/ScenarioStepContextTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/StepExecutionTestsBase.cs
Tests/TechTalk.SpecFlow.RuntimeTests/StronglyTypedContextAcessorTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/TestRunnerManagerRunnerCreationTests.cs
Tests/TechTalk.SpecFlow.Specs/Features/Contexts/FeatureInfo/Description.feature
Tests/TechTalk.SpecFlow.Specs/Features/Contexts/ScenarioInfo/Arguments.feature
Tests/TechTalk.SpecFlow.Specs/Features/Contexts/ScenarioInfo/Description.feature
changelog.txt

This PR adds new `Arguments` property to `ScenarioInfo` class and populates it on test generation side.
Fixes: #1955 , #1890 
Changes:
- `ScenarioInfo` class has new `Arguments` property
- Added tests to verify `Arguments` property is filled in correctly
- Reuse `tagsOfScenario` variable to construct `ScenarioInfo` object with less memory allocation

Scenario info arguments

---

TechTalk.SpecFlow.Generator/Plugins/GeneratorPluginLoader.cs
TechTalk.SpecFlow.Generator/Plugins/PluginAssemblyResolver.cs
TechTalk.SpecFlow.Generator/TechTalk.SpecFlow.Generator.csproj
changelog.txt

Use AssemblyLoadContext for loading the generator plugin and resolve deps in case of netcoreapp

---

README.md

add supported .NET Versions

---

Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/SpecFlow.MsTest.targets
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/SpecFlow.NUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/SpecFlow.xUnit.targets
SpecFlow.Tools.MsBuild.Generation/ReplaceTokenInFileTask.cs
changelog.txt

This change introduces a property that controls if the ReplaceTokenInFileTask should write the contents if it's not changed. This will improve performance as a project with xunit/nunit/msbuild integration before this fix will trigger a recompile on every build if the file is always changed

Only write contents when it's changed

---

TechTalk.SpecFlow/Infrastructure/ContainerBuilder.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/ContainerBuilderTests.cs
changelog.txt

We are generating on-the-fly assemblies containing the tests to be executed. This used to be working in past versions (2.4). Some changes introduced since then prevent us from using our dynamic assemblies successfully.
The reason is that Assembly.Location is retrieved and is not supported by dynamic assemblies (see [here](https://referencesource.microsoft.com/#mscorlib/system/reflection/assembly.cs,1131)).

Support dynamic assemblies in container initialization

---

docs/Integrations/xUnit.md

- added new line after using statements
- fixed code example
- used class name as constructor name
- use instance var in method

fixed code example

---

CONTRIBUTING.md

There was weird symbol inside `Contributing.MD` just before `recurse-submodules`. It was causing weird errors and I could not figure out first what was causing it. I changed it to double dash and it should work again properly.

fix dash symbol in Contributing.md

---

TechTalk.SpecFlow/Assist/ValueRetrievers/ListValueRetriever.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/ListRetrieverTests.cs

Added support for `IReadOnlyList` to `ListValueRetriever`

Added IReadOnlyList to types handled by ListValueRetriever

---

Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/MSTest.AssemblyHooks.template.cs
Plugins/TechTalk.SpecFlow.MSTest.SpecFlowPlugin/MsTestContainerBuilder.cs
Tests/TechTalk.SpecFlow.Specs/Features/UnitTestProviderSpecific/MsTest/TestContext.feature
changelog.txt
docs/Integrations/MsTest.md

PR for issue #1859 
This feature enables access to the TestContext in the BeforeTestRun/AfterTestRun simply via parameter injection:
``` csharp
[BeforeTestRun]
public static void BeforeTestRun(TestContext testContext)
{
//you can access the TestContext injected as parameter
testContext.WriteLine(testContext.TestRunDirectory);
}
```

Be able to access MSTest TestContext in BeforeTestRun/AfterTestRun #1859

---

Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/SpecFlow.ExternalData.SpecFlowPlugin.csproj

Reference the Generator project directly to avoid version conflicts with the SpecFlow.dll in the generated nuget packages
Fixes #2218

Fix the SpecFlow reference in the ExternalData plugin

---

TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
TechTalk.SpecFlow/ScenarioContext.cs
TechTalk.SpecFlow/SpecFlowContext.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineRuntimePluginEventsTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
changelog.txt

Enable plugins to act on execution events even if a (user-)hook fails with an exception.
* Catch exception thrown by the hooks
* Store hook exception in TestError of the corresponding context (if no previous error captured yet)
* Call plugin hooks even if user-hooks failed with an exception
* Throw original hook exception after the plugin hooks finished so that the test fails with the original error
* Set ScenarioExecutionStatus to TestError if a scenario level hook failed

Capture hook errors and call plugin hooks after hook error

---

Plugins/SpecFlow.Autofac.SpecFlowPlugin/AutofacTestObjectResolver.cs
changelog.txt

Fix for #2307 .
This PR only solves the problem with injecting contexts in static hooks (i.e. AfterFeature)

#2307 Fixed bug when feature context can't be resolved at static methods

---

docs/Bindings/ScenarioContext.md

This PR adds documentation changes requested in issue #2144 that illustrate accessing scenario examples from ScenarioInfo.
Also, a small change was made to an existing mention of retrieving tags from the same object, aimed at pointing out that both feature and scenario tags are returned.
- [ x] Other (docs, build config, etc)

add section on retrieving escenaio examples from ScenarioInfo

---

TechTalk.SpecFlow/Plugins/RuntimePluginLoader.cs
TechTalk.SpecFlow/Plugins/RuntimePluginLocationMerger.cs
TechTalk.SpecFlow/Plugins/RuntimePluginLocator.cs
TechTalk.SpecFlow/StringExtensions.cs
Tests/TechTalk.SpecFlow.PluginTests/RuntimePluginLocatorTests.cs
changelog.txt

Improves the logic in RuntimePluginLocator by 
- checking whether we already added the target directory before searching for files on the filesystem
- avoiding various temporary allocations
Improves the logic in RuntimePluginLocationMerger by
- reducing allocations in the common case
I've profiled the existing test called RuntimePluginLocatorTests.LoadPlugins_Find_TestAssembly to test improvements.
Before:
After:
Things to look for:
- Takes overall less time (7ms -> 2 ms) (Keep in mind this is under a profiler)
- SearchPluginsInFolder is only called once instead of 3 times (due to all 3 directories being the same)
- Merger does not have a static constructor being called anymore and overall reduced time (due to not some Linq functions)
- IsNotNullOrWhiteSpace is much faster (due to the …

improve RuntimePlugin Locator and LocationMerger

---

docs/Extend/Plugins.md

I have changed the (incorrect) code snippets in the Plugins documentation page to match the (correct) text describing them.
I've created another PR in the samples project https://github.com/SpecFlowOSS/SpecFlow-Examples/pull/68 to correct the same changes there too.
- [n/a] I've added tests for my code. (most of the time mandatory)
- [n/a] I have added an entry to the changelog. (mandatory)
- [n/a] My change requires a change to the documentation.

Change Plugins docs to use correct framework monikers

---

TechTalk.SpecFlow/Bindings/BindingInvoker.cs
TechTalk.SpecFlow/CultureInfoScope.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/CultureInfoScopeTests.cs
changelog.txt

Changes the CultureInfoScope to a readonly struct to avoid an extra allocation.
Also slightly improve performance by only reading the current cultureInfo only once instead of multiple times.

improve CultureInfoScope

---

build.yml

WhiteSource Bolt is not reporting since December 2019. As I found out the problem was that we are using an older version of the WS Bolt build task. After updating it to the latest (version 20), it works again.
I added a condition to scan the Open Source Components only during the Windows build (no value to scan the same stuff for Linux as well). Also I added a timeout to the WhiteSource Bolt task, because there are builds where the WS Bolt task took 30 mins to complete (and even after that time it was timed out).

Fix WhiteSource Bolt reporting

---

TechTalk.SpecFlow/Plugins/PluginAssemblyResolver.cs
changelog.txt

During the Assembly's `OnResolving` method the `_dependencyContext` can be null, so check for that.
Fixes #2344 #2403

Add null check for DependencyContext

---

Templates/TechTalk.SpecFlow.Templates.DotNet/templates/SpecFlowProject/Template.csproj
changelog.txt

The LivingDoc plugin reference needs to be in sync with the SpecFlow major/minor version.
The fix uses the major/minor of SpecFlow in the meta template to automatically keep in sync (similarly to the Runner reference).

Auto update livingdoc reference major/minor in "dotnet new" template

---

Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/SpecFlow.xUnit.targets

Marking the task to run before the CoreCompile fixes the errors. 
Tested with VS2019 v16.9.6 and JetBrains Rider 2021.1.0 (#RD-211.6556.17)
See also: https://stackoverflow.com/a/62516447/872395
Fixes #1825

Fix the "phantom" errors in IntelliSense and Resharper when using Xunit

---

Tests/TechTalk.SpecFlow.GeneratorTests/UnitTestProvider/XUnit2TestGeneratorProviderTests.cs

Fixes a unit test that should have been failing, but wasn't.
I've verified that this unit test can fail :)

Fix xunit2 generator test for NonParallelizable collection attribute.

---

TechTalk.SpecFlow/Infrastructure/ContainerBuilder.cs
TechTalk.SpecFlow/Plugins/IRuntimePluginLoader.cs
TechTalk.SpecFlow/Plugins/RuntimePluginLoader.cs
Tests/TechTalk.SpecFlow.PluginTests/Infrastructure/WindsorPluginTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/PluginTests.cs
changelog.txt

Should not log error if TestAssembly does not have a RuntimePlugin attribute

---

docs/Extend/Value-Retriever.md

Fixed a typo in the Value Retrievers documentation page. Changed Registr to Register.
Fixes issue #2544

Fix typo in Value Retrievers doc: change Registr to Register

---

TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
changelog.txt

Make XUnit2TestGeneratorProvider.SetTestMethod virtual so that it can be replaced by generator plugins.
I needed to make this change for a new feature in my generator plugin, src using it here: https://github.com/JoshKeegan/xRetry/blob/5494809b736bc50c8bcdf24ece71b6623a2f6d4c/src/xRetry.SpecFlow/TestGeneratorProvider.cs#L35

Make XUnit2TestGeneratorProvider.SetTestMethod virtual

---

TechTalk.SpecFlow.Generator/UnitTestProvider/NUnit3TestGeneratorProvider.cs
changelog.txt

Changed NUnit3TestGeneratorProvider.SetTestMethod() and NUnit3TestGeneratorProvider.SetRowTest() to virtual. This will enable them to be overriden in generator plugins.
**Why?**
XUnit2TestGeneratorProvider has these methods virtual. This enables overriding but keeping the ability to invoke base methods' code. 
This enables generator plugin devs to add additional functionality such as adding custom attributes during tag discovery in various situations (scenarios/scenario outlines/features/with tag/without tag). 
NUnit3TestGeneratorProvider hasn't these methods virtual. Therefore, anyone who would want to override functionality, had to copy the entire NUnit3TestGeneratorProvider's body, and then add desired additional functionality. This could cause 3rd party generator plugins to be prone …

Changed NUnit3TestGeneratorProvider.SetTestMethod() and NUnit3TestGeneratorProvider.SetRowTest() to virtual

---

TechTalk.SpecFlow/Assist/ValueRetrievers/DateTimeOffsetValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/DateTimeValueRetriever.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/DateTimeOffsetValueRetrieverTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/DateTimeValueRetrieverTests.cs
changelog.txt
docs/Bindings/SpecFlow-Assist-Helpers.md

This change adds a way to modify the DateTimeStyles used when parsing.

add DateTimeStyles to DateTime(Offset)ValueRetriever

---

TechTalk.SpecFlow/Tracing/TestTracer.cs
changelog.txt

The intent of this change is to modify the output of the duration string to milliseconds if it's below a certain threshold.
(This is useful when the steps you execute are in the milliseconds range, so outputting 0.1s isn't particularly useful)

adjusted duration output to milliseconds

---

TechTalk.SpecFlow/TagHelper.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TagHelperTests.cs
changelog.txt

Fixes a bug that has been introduced in the latest release as part of #2410 causing tests with an @ignore tag to still be run.

Bug fix: @ignore tag check was looking for the wrong value

---

docs/Bindings/Step-Definitions.md

The Step Definition Methods Rules section states that "method can not have a return type or have a `Task` as return type". I tried to change my method to return `int` instead of `void` and it works without errors. So I guess if it's not a rule which would cause an error than it should be rather recommendation than rule.
If it's a bug that SpecFlow should catch, I can provide you steps to reproduce it (although it's a very simple 😀)

Update rules for step definitions methods

---

Plugins/SpecFlow.Autofac.SpecFlowPlugin/AutofacPlugin.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/AutofacTestObjectResolver.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/ContainerBuilderExtensions.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/ContainerBuilderFinder.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/GlobalDependenciesAttribute.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/IContainerBuilderFinder.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/ScenarioDependenciesAttribute.cs
changelog.txt
docs/Integrations/Autofac.md

…tional Attribute and two new method signatures.

Autofac global container

---

TechTalk.SpecFlow/Assist/ValueRetrievers/ListValueRetriever.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/ListRetrieverTests.cs

The intent of this change is to support IReadOnlyCollection binding for ListValueRetriever #2497.

Support IReadOnlyCollection binding for ListValueRetriever

---

docs/Bindings/SpecFlow-Assist-Helpers.md

Silly spelling mistake that, of course, I only noticed after my last PR was completed and deployed.
Changed Ba`c`kAccount to Ba`n`kAccount.

Corrected misspelled word

---

TechTalk.SpecFlow/ISpecFlowOutputHelper.cs
Tests/TechTalk.SpecFlow.Specs/Features/Contexts/ContextInjection.feature
Tests/TechTalk.SpecFlow.Specs/Support/OutputConnector.cs
changelog.txt

It was in namespace `TechTalk.SpecFlow.Infrastructure` that is an internal namespace and not suppose to be needed for regular end users. Technically it is a breaking change, but users of `ISpecFlowOutputHelper` surely had the `TechTalk.SpecFlow` namespace, e.g. for the `[Given/When/Then]` attributes.

Move interface ISpecFlowOutputHelper to the TechTalk.SpecFlow namespace

---

docs/Bindings/SpecFlow-Assist-Helpers.md

Add tip for step argument conversions to NullValueRetriever docs

---

Plugins/SpecFlow.Autofac.SpecFlowPlugin/AutofacPlugin.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/AutofacTestObjectResolver.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/ContainerBuilderFinder.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/FeatureDependenciesAttribute.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/IContainerBuilderFinder.cs
docs/Integrations/Autofac.md

The use case for this change is when running a specflow test suite that tests an ASP.NET Core application using Autofac internally.  Specflow should be able to use all the existing registrations in the application container, and then be able to override specific registrations (for proxying services), register the bindings, and contexts.
Let me know your thoughts, thanks!
For example:
```c#
// Top-level Program.cs
var builder = WebApplication.CreateBuilder(args);
builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());
builder.Host.ConfigureContainer<ContainerBuilder>(x =>
{
// TODO: Add types and modules
});
var app = builder.Build();
app.MapGet("/weatherforecast", () => new object());
app.Run();
```
```c#
// SpecFlow scaffolding handling app startup/shutdown
[Binding] …
```

Allow Autofac plugin to provide existing lifetime scope

---

TechTalk.SpecFlow/Bindings/StepDefinitionRegexCalculator.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/StepDefinitionRegexCalculatorTests.cs

Fix: Method-name based step definition does not match end of line.

---

TechTalk.SpecFlow.Generator/Generation/UnitTestMethodGenerator.cs

Ensure that calls to `FeatureBackgroundAsync` are awaited when called, i.e. 
Instead of this
```csharp
// ... snip ...
#line 4
this.FeatureBackgroundAsync();
#line hidden
// ... snip ...
```
Generate this
```csharp
// ... snip ...
#line 4
await this.FeatureBackgroundAsync();
#line hidden
// ... snip ...
```
--- 
Note: I've not added tests or an entry to the change log for the following reasons:
- There are no existing tests for the UnitTestMethodGenerator; if you require them then i can have a look to create some
- I've not added an entry to the changelog as this fixes a change within the 4.0.16-beta version, as such it fixes an issue during the beta. Once again if this is required, please let me know and i'll add something in.

#2608: Await the call to FeatureBackgroundAsync

---

TechTalk.SpecFlow/Bindings/AsyncMethodHelper.cs
TechTalk.SpecFlow/Bindings/BindingDelegateInvoker.cs
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/BindingInvokerTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/StepTransformationTests.cs
changelog.txt
docs/Bindings/Asynchronous-Bindings.md

Support for ValueTask and ValueTask<T> binding methods (step definitions, hooks, step argument transformations). For step argument transformations #2660 is needed.

Support for ValueTask and ValueTask<T> async binding methods.

---

TechTalk.SpecFlow/Bindings/AsyncMethodHelper.cs
TechTalk.SpecFlow/Bindings/BindingInvoker.cs
TechTalk.SpecFlow/Bindings/Discovery/BindingSourceProcessor.cs
Tests/TechTalk.SpecFlow.RuntimeTests/BindingSourceProcessorStub.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/BindingInvokerTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/Discovery/BindingSourceProcessorTests.cs
changelog.txt

Fixes #2657 by explicitly disallowing `async void` binding methods.

Disallow async void bindings 2657

---

TechTalk.SpecFlow/Bindings/BindingError.cs
TechTalk.SpecFlow/Bindings/BindingRegistry.cs
TechTalk.SpecFlow/Bindings/Discovery/BindingSourceMethod.cs
TechTalk.SpecFlow/Bindings/Discovery/BindingSourceProcessor.cs
TechTalk.SpecFlow/Bindings/Discovery/BindingSourceType.cs
TechTalk.SpecFlow/Bindings/Discovery/RuntimeBindingRegistryBuilder.cs
TechTalk.SpecFlow/Bindings/Discovery/RuntimeBindingSourceProcessor.cs
TechTalk.SpecFlow/Bindings/IBindingRegistry.cs
TechTalk.SpecFlow/Bindings/InvalidStepDefinitionBindingBuilder.cs
TechTalk.SpecFlow/Bindings/Reflection/BindingType.cs
TechTalk.SpecFlow/Bindings/Reflection/RuntimeBindingMethod.cs
TechTalk.SpecFlow/Bindings/Reflection/RuntimeBindingType.cs
TechTalk.SpecFlow/ErrorHandling/ErrorProvider.cs
TechTalk.SpecFlow/Infrastructure/StepDefinitionMatchService.cs
TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
Tests/TechTalk.SpecFlow.RuntimeTests/BindingSourceProcessorStub.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/Discovery/BindingSourceProcessorTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/ErrorProviderTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
changelog.txt

Some generic binding errors (e.g. `[Binding]` on a generic type) were not properly reported as errors so far, only as warnings, but those are usually not visible by test runners. Some of these errors were causing strange exceptions during execution, but it was hard to trace them back to the source problem.
Also type load exceptions blocked the discovery process that causes problems with tooling (e.g. VS) that uses the binding registry builder to discover the step definitions.
This PR introduces validity of loaded binding registry and provides a way to query these errors from the binding registry. During test execution, the invalid binding registry fails the tests by listing all collected error.

Report binding problems to binding registry and show them as errors during test execution

---

TechTalk.SpecFlow/Bindings/AsyncMethodHelper.cs
TechTalk.SpecFlow/Bindings/BindingDelegateInvoker.cs
TechTalk.SpecFlow/Bindings/BindingInvoker.cs
TechTalk.SpecFlow/Bindings/ExecutionContextHolder.cs
TechTalk.SpecFlow/Bindings/IBindingDelegateInvoker.cs
TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/BindingInvokerTests.cs

This PR fixes #2600 by saving and reusing the ExecutionContext for the subsequent binding method invocations. ExecutionContext is pretty complex and hard to understand and also the behavior of `AsyncLocal<T>` is not straightforward to understand. 
The bottom line is: `AsyncLocal<T>` now works as in SpecFlow v3 (and is it supposed to): you can change the value in ctor and sync step definitions, but the changes in async step definitions are discarded (this is how ExecutionContext works).
If you want to use  `AsyncLocal<T>` and be able to change it in sync/async step definitions, you should use  `AsyncLocal<StrongBox<T>>` and initialize it in ctor, like:
```
private readonly AsyncLocal<StrongBox<string>> _boxedAsyncLocal = new() { Value = new StrongBox<string>("ctor-value") };
```
A bit more …

Fix #2600 by preserving ExecutionContext and reuse it for subsequent binding method invocations

---

docs/Bindings/Step-Definitions.md

The sentence "Shouldn't have a return type or have `Task` as return type." can be read in two ways:
1. Should not have a return type nor return `Task`
2. Should not have a return type OR should return `Task`
So a minor change to make it more clear and direct.

Clarify that `Task` is a valid return type in Step
