SpecFlowOSS/SpecFlow

Runtime/BindingSkeletons/StepTextAnalyzer.cs

Use a delimiter-aware RegEx when creating attributes to avoid broad and accidental matching of steps, which can occur with the default (.*) RegEx.
This is the fix requested to be placed in the V2 branch - more than happy to help :)

Fix For Issue #309

---

Runtime/Assist/Service.cs
Runtime/Assist/ValueRetrievers/NullableTimeSpanValueRetriever.cs
Runtime/Assist/ValueRetrievers/TimeSpanValueRetriever.cs
Runtime/TechTalk.SpecFlow.csproj
Tests/RuntimeTests/AssistTests/ServiceTests.cs
Tests/RuntimeTests/AssistTests/ValueRetrieverTests/NullableTimespanValueRetrieverTests.cs
Tests/RuntimeTests/AssistTests/ValueRetrieverTests/TimeSpanValueRetrieverTests.cs
Tests/RuntimeTests/RuntimeTests.csproj
Tests/TechTalk.SpecFlow.Specs/packages.config

Add support for timespan in SpecFlow.Assist
Per request from #493

Timespan support in assist

---

Reporting/BindingCollector.cs

Fixed defect Step definition report does not support external step assemblies

---

Generator/UnitTestProvider/XUnitTestGeneratorProvider.cs

Actually this is PR #484 redone for v2.

Pr484 on v2

---

Tests/RuntimeTests/AssistTests/ExampleEntities/Person.cs
Tests/RuntimeTests/AssistTests/TableHelperExtensionMethods/CreateSetHelperMethodTests.cs

2 tests for some breaking changes in TechTalk.SpecFlow.Assist. TableHelperExtensionMethods.CreateSet<T>

Assists breaking changes

---

Tools/MsBuild/TaskBase.cs

to the ones that are shipped with the SpecFlow.exe/MSBuild task

Resolve TechTalk.SpecFlow* assemblies in MSBuild Task

---

Runtime/Assist/SafetyTableDiffExceptionBuilder.cs
Tests/RuntimeTests/AssistTests/SafetyTableDiffExceptionBuilderTests.cs

It's only been this way for FIVE YEARS :scream: 
Sorry about that. :sweat_smile:

Missing a word.

---

appveyor.yml

test pr to test build infrastructure (WIP)

---

Runtime/Bindings/BindingRegistry.cs
Runtime/Infrastructure/BindingInstanceResolver.cs
Runtime/Infrastructure/DefaultDependencyProvider.cs
Runtime/Infrastructure/IBindingInstanceResolver.cs
Runtime/ScenarioContext.cs
Runtime/TechTalk.SpecFlow.csproj
Tests/RuntimeTests/Bindings/BindingRegistryTests.cs
Tests/RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/RuntimeTests/RuntimeTests.csproj
Tests/RuntimeTests/ScenarioContextExtensions.cs
Tests/RuntimeTests/ScenarioContext_BindingInstancesTest.cs
Tests/RuntimeTests/StepExecutionTestsBase.cs
Tests/RuntimeTests/StepTransformationTests.cs
Tests/RuntimeTests/StronglyTypedContextAcessorTests.cs
Tests/RuntimeTests/TestObjectFactories.cs
changelog.txt

This infrastructure improvement can be used later for supporting other DI libraries for binding instances.

Allow binding resultion be customized

---

Generator/UnitTestProvider/IUnitTestGeneratorProvider.cs
Generator/UnitTestProvider/NUnit3TestGeneratorProvider.cs
Generator/UnitTestProvider/NUnitTestGeneratorProvider.cs
Tests/GeneratorTests/CodeDomExtensions.cs
Tests/GeneratorTests/GeneratorTests.csproj
Tests/GeneratorTests/IUnitTestGeneratorProviderExtensions.cs
Tests/GeneratorTests/MsTestGeneratorProviderTests.cs
Tests/GeneratorTests/NUnit3GeneratorProviderTests.cs

Works towards resolving #612 
There are no automated tests yet, because I don't know where to begin with one. any input is appreciated.

[Please Review] Use correct NUnit3 attributes

---

Runtime/Assist/ValueRetrievers/EnumValueRetriever.cs
Runtime/Bindings/StepArgumentTypeConverter.cs

This fixes what I noticed with #661, that this tiny bit of logic is duplicated in two spots.  This is not a big deal.

Consolidate this enum logic.

---

TechTalk.SpecFlow.Generator/UnitTestFeatureGenerator.cs
TechTalk.SpecFlow.Parser.Compatibility/CompatibleAstConverter.cs
TechTalk.SpecFlow.Parser/SpecFlowDocument.cs
TechTalk.SpecFlow.Parser/SpecFlowFeature.cs
TechTalk.SpecFlow.Parser/SpecFlowGherkinParser.cs
TechTalk.SpecFlow.Reporting/StepDefinitionReport/StepDefinitionReportGenerator.cs
Tests/TechTalk.SpecFlow.GeneratorTests/ParserHelper.cs
Tests/TechTalk.SpecFlow.GeneratorTests/XUnitTestGeneratorProviderTests.cs

Fix for #666

---

TechTalk.SpecFlow.Generator/Project/MsBuildProjectReader.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/InputProjectDriver.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/MsBuild/ProjectCompiler.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/MsBuild/ProjectGenerator.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/StepBindingInput.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/Templates/BindingClass.vb
Tests/TechTalk.SpecFlow.Specs/Drivers/Templates/Bindings.vb
Tests/TechTalk.SpecFlow.Specs/Drivers/Templates/TestProjectFile.vbproj
Tests/TechTalk.SpecFlow.Specs/Features/LanguageSupport.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/BindingSteps.cs
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/ProjectSteps.cs
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj

The MSBuild integration generates at the moment only C# code.
This PR enables it, that it also generates VB.Net code.

Vb.Net code generation in ms build task

---

CONTRIBUTING.md

[WIP] Contribution guide

---

Tests/TechTalk.SpecFlow.RuntimeTests/ScenarioStepContextTests.cs

Improve test readability

---

TechTalk.SpecFlow/Assist/ValueRetrievers/NullableDateTimeOffsetValueRetriever.cs

Did not check Nullable<> correctly.

Fixed CanRetrieve of NullableDateTimeOffsetValueRetriever

---

CONTRIBUTING.md

As discussed during the last issue walkthrough.

Enhancements to Contributing.md with regard to style

---

TechTalk.SpecFlow/Assist/EnumerableProjection.cs
TechTalk.SpecFlow/Assist/PropertyExtensionMethods.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ProjectionTests.cs
changelog.txt

Fix for #771: Projection<T>.Equals() bug

---

TechTalk.SpecFlow.Reporting/NUnitExecutionReport/NUnitExecutionReportGenerator.cs

bug fix #739
add support to nunit3 test output (console output)

bug fix #739 add support to nunit3 test output

---

TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
Tests/TechTalk.SpecFlow.GeneratorTests/GeneratorTests.csproj
Tests/TechTalk.SpecFlow.GeneratorTests/XUnit2TestGeneratorProviderTests.cs

Added xunit theory display name attribute and wrote additional test to verify display name was added for TheoryAttribute. #723 based on previous #557 implementation

Added display name for theory attribution

---

TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
Tests/TechTalk.SpecFlow.Specs/Features/ScopedHooks.feature

Hook should only be executed once.

Hook with multiple Tags scoped are executed more than once

---

docs/issue

Issue reporting template first draft

Issue Template

---

.gitattributes
.gitignore

also add .vs folder to .gitignore for vs 2017 users

Turn off line ending git auto conversion

---

README.md

Remove ambiguity regarding where to go for questions.

Add hyperlink to discussion group

---

TechTalk.SpecFlow/Assist/ValueRetrievers/EnumValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableBoolValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableByteValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableCharValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableDateTimeOffsetValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableDateTimeValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableDecimalValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableDoubleValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableFloatValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableGuidValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableIntValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableLongValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableSByteValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableShortValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableTimeSpanValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableUIntValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableULongValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/NullableUShortValueRetriever.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/StringValueRetriever.cs

can be overwritten to get rid of special characters

ValueRetriever improvement suggestions

---

TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.targets

https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-build-incrementally

Enable increment MSBuild support

---

TechTalk.SpecFlow/PlatformSpecific/UnitTestProviders.cs
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
TechTalk.SpecFlow/UnitTestProvider/MsTestV2RuntimeProvider.cs

missed this when creating the mstest.v2 generator provider.

Adding mstest.v2 unit test provider

---

Installer/NuGetPackages/SpecFlow/SpecFlow.nuspec

Fix System.ValueTuple version

---

Installer/NuGetPackages/.build/build.targets

fix msbuild integration, encoding issues in targets file

---

TechTalk.SpecFlow.Tools/MsBuild/GeneratorTask.cs
TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.props
TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.targets

add property for msbuild generate task to start debugger

Make MSBuild Task debuggable

---

TechTalk.SpecFlow.Parser/ISemanticValidator.cs
TechTalk.SpecFlow.Parser/SemanticValidators/DuplicateExamplesValidator.cs
TechTalk.SpecFlow.Parser/SemanticValidators/DuplicateScenariosValidator.cs
TechTalk.SpecFlow.Parser/SemanticValidators/MissingExamplesValidator.cs
TechTalk.SpecFlow.Parser/SpecFlowGherkinParser.cs
TechTalk.SpecFlow.Parser/TechTalk.SpecFlow.Parser.csproj

This addresses #1105
The validators are extracted but are not resolved by DI. This can be added after https://github.com/techtalk/SpecFlow/pull/1143 is merged to master.

Validators extracted from SpecFlowGherkinParser private methods

---

Installer/NuGetPackages/SpecFlow.MsTest/SpecFlow.MsTest.nuspec.props
Installer/NuGetPackages/SpecFlow.xUnit/build/SpecFlow.xUnit.props
Plugins/TechTalk.SpecFlow.MSTest.SpecFlowPlugin/MSTestTraceListener.cs
Plugins/TechTalk.SpecFlow.MSTest.SpecFlowPlugin/RuntimePlugin.cs
Plugins/TechTalk.SpecFlow.MSTest.SpecFlowPlugin/TechTalk.SpecFlow.MSTest.SpecFlowPlugin.csproj
TechTalk.SpecFlow/Configuration/AppConfig/RuntimeConfigElement.cs
TechTalk.SpecFlow/Configuration/JsonConfig/Dependency.cs
TechTalk.SpecFlow/Configuration/JsonConfig/JsonConfigurationLoader.cs
TechTalk.SpecFlow/Configuration/JsonConfig/RuntimeElement.cs
TechTalk.SpecFlow/Infrastructure/ContainerBuilder.cs
TechTalk.SpecFlow/Plugins/IRuntimePluginLoader.cs
TechTalk.SpecFlow/Plugins/RuntimePluginLoader.cs
TechTalk.SpecFlow/Plugins/RuntimePluginLocator.cs
Tests/TechTalk.SpecFlow.GeneratorTests/ConfigurationTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/App.config
Tests/TechTalk.SpecFlow.RuntimeTests/Configuration/AppConfigTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Configuration/JsonConfigTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/PluginTests.cs
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/Combination.cs
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/CustomXUnitGeneratorProvider.cs
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/TestRunCombinations.cs
Tests/TechTalk.SpecFlow.Specs/Features/Execution/Configuration.feature
Tests/TechTalk.SpecFlow.Specs/Features/Execution/InAppDomainParallelExecution.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/ExecutionResultSteps.cs
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/ExecutionSteps.cs

Dot net core specs

---

TechTalk.SpecFlow/FeatureContext.cs
TechTalk.SpecFlow/ScenarioContext.cs

mark Scenario/FeatureContext.Current as obsolete

---

TechTalk.SpecFlow.Reporting/NUnitExecutionReport/NUnitExecutionReport.xslt
Tests/TechTalk.SpecFlow.Specs/Features/Reports/ExecutionReport.feature

* Also make a right panel possible for results other than failure.
Issue #871

Show warnings in NUnit test execution reports.

---

TechTalk.SpecFlow.Tools/MsBuild/TechTalk.SpecFlow.props
Tests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests/CodeBehindFileGenerationTests.cs
changelog.txt

@DanielTheCoder: will be this enough?

fixed UpToDateChecks for feature files in MSBuild target

---

Installer/TechTalk.SpecFlow.CustomPlugin/SpecFlow.CustomPlugin.nuspec

Added references to
- System.Threading.Tasks.Dataflow
- System.Collections
- System.Diagnostics.Debug
- System.Runtime.Extensions
- System.Security.Principal
- System.Net.Primitives
- System.IO.FileSystem
- System.CodeDom

Add missing dependencies for SpecFlow.CustomPlugin package

---

TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/XUnitTestGeneratorProvider.cs
Tests/TechTalk.SpecFlow.Specs/Features/UnitTestProviderSpecific/XUnit/XUnit2Provider.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/FeatureFileSteps.cs

Added class level feature tag in the form of "xunit:collection(<COLLECTION>)". This adds "[Xunit.Collection("COLLECTION")]" into the feature.cs class attributes during code behind file generation. 
Non breaking change.
- [ X] New feature (non-breaking change which adds functionality).
- [x ] My change requires a change to the documentation.

collection class attribute addition

---

docs/MSBuild Code Behind File Generation.md

add new documentation for MSBuild

---

TechTalk.SpecFlow/Assist/SpecFlowDefaultValueRetrieverList.cs
TechTalk.SpecFlow/Assist/ValueRetrievers/UriValueRetriever.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ServiceTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/EnumerableRetrieverTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/UriValueRetrieverTests.cs
changelog.txt

An Uri type value retriever. An empty string is parsed as empty Uri to be consistent with string behavior.
- [ X ] New feature (non-breaking change which adds functionality).
- [ X ] I've added tests for my code.
- [ X ] I have added an entry to the changelog

Uri value retriever

---

TechTalk.SpecFlow/PlatformCompatibility/MonoHelper.cs
TechTalk.SpecFlow/StringExtensions.cs
TechTalk.SpecFlow/VersionInfo.cs

Made the extension methods from Issue #1400 internal.

Make extension APIs internal #1400

---

TechTalk.SpecFlow/PlatformCompatibility/CultureInfoHelper.cs
TechTalk.SpecFlow/PlatformCompatibility/EnumHelper.cs
TechTalk.SpecFlow/PlatformCompatibility/ExceptionHelper.cs
TechTalk.SpecFlow/StringExtensions.cs

Fresh PR as requested for the usings-cleanup and string/String unification

Clean up some using statements and unify keyword-usage

---

SpecFlow.Tools.MsBuild.Generation/SpecFlow.Tools.MsBuild.Generation.csproj
SpecFlow.Tools.MsBuild.Generation/build/CPS/Buildsystem/CpsExtension.DesignTime.targets
SpecFlow.Tools.MsBuild.Generation/build/CPS/Buildsystem/Rules/FeatureFileType.xaml
SpecFlow.Tools.MsBuild.Generation/build/CPS/Buildsystem/Rules/ProjectItemsSchema.xaml
SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.props
SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.targets
Tests/TechTalk.SpecFlow.RuntimeTests/TraceListenerQueueTests.cs
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
azure-pipelines.yml
build.ps1
build.yml

This registers `.feature` files to the CPS so it is not removed from the `SpecFlowFeatureFiles` ItemGroup

add registration to CPS to NuGet package

---

azure-pipelines.yml
build.ps1
build.yml

Building on vs2019

---

CONTRIBUTING.md
docs/Development.md
docs/development/Coding Style.md
docs/development/Definition of Terms.md
docs/development/Dependencies.md
docs/development/LocalSetup.md
docs/development/Projects.md
docs/development/SpecialFiles.md
docs/development/potentialProblems.md

to help newcomers to contribute to SpecFlow

[Documentation] improve Development documentation

---

azure-pipelines.yml
version.json

set correct build number for release automation

automate GitHub release

---

SpecFlow.Tools.MsBuild.Generation/build/CPS/Buildsystem/Rules/FeatureFileType.xaml
changelog.txt

resolves https://github.com/techtalk/SpecFlow/issues/1508

add "Custom Tool" back to the property page

---

Plugins/SpecFlow.Autofac.SpecFlowPlugin/AutofacPlugin.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/AutofacTestObjectResolver.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/BindingRegistryExtensions.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/ContainerBuilderFinder.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/IContainerBuilderFinder.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/ScenarioDependenciesAttribute.cs
Plugins/SpecFlow.Autofac.SpecFlowPlugin/SpecFlow.Autofac.SpecFlowPlugin.csproj
Plugins/SpecFlow.Autofac.SpecFlowPlugin/SpecFlow.Autofac.nuspec
Plugins/SpecFlow.Autofac.SpecFlowPlugin/build/SpecFlow.Autofac.props
Plugins/SpecFlow.Autofac.SpecFlowPlugin/build/SpecFlow.Autofac.targets
TechTalk.SpecFlow.sln

Merge the SpecFlow Autofac plugin into the core repo

Add SpecFlow.Autofac from https://github.com/gasparnagy/SpecFlow.Autofac

---

TechTalk.SpecFlow/CucumberMessages/CucumberMessageSender.cs
TechTalk.SpecFlow/CucumberMessages/ITestAmbiguousMessageFactory.cs
TechTalk.SpecFlow/CucumberMessages/TestAmbiguousMessageFactory.cs
TechTalk.SpecFlow/CucumberMessages/TestResultFactory.cs
TechTalk.SpecFlow/Infrastructure/DefaultDependencyProvider.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/TestResultFactoryTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/CucumberMessages/TestSuiteSetupDriver.cs
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/CucumberMessages/ScenarioSteps.cs

add support for test case finished on ambiguous scenarios

---

TechTalk.SpecFlow/CucumberMessages/ITestResultFactory.cs
TechTalk.SpecFlow/CucumberMessages/ITestUndefinedMessageFactory.cs
TechTalk.SpecFlow/CucumberMessages/TestResultFactory.cs
TechTalk.SpecFlow/CucumberMessages/TestUndefinedMessageFactory.cs
TechTalk.SpecFlow/Infrastructure/DefaultDependencyProvider.cs
TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/TestResultFactoryTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/CucumberMessages/TestSuiteSetupDriver.cs
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/CucumberMessages/ScenarioSteps.cs

test case finished for undefined scenarios

---

Build/Versioning.targets
TechTalk.SpecFlow.Generator/TestGeneratorFactory.cs
version.json

change version to 3.1

---

TechTalk.SpecFlow/TechTalk.SpecFlow.ExternalAnnotations.xml

Additional attribute annotations for ReSharper

---

TechTalk.SpecFlow/Bindings/AsyncHelpers.cs
TechTalk.SpecFlow/Configuration/ObsoleteBehavior.cs
TechTalk.SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj

- also suppress missing XML comment warnings and fix some invalid XML warnings in AsyncHelpers and ObsoleteBehavior
Implements #1014

Generate XML Documentation and include in NuGet package

---

Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/SpecFlow.xUnit.nuspec
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/SpecFlow.xUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/xUnit.AssemblyHooks.cs
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/xUnit.AssemblyHooks.vb
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/AssemblyFixtureAttribute.cs
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/TechTalk.SpecFlow.xUnit.SpecFlowPlugin.csproj
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/XunitTestAssemblyRunnerWithAssemblyFixture.cs
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/XunitTestCollectionRunnerWithAssemblyFixture.cs
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/XunitTestFrameworkExecutorWithAssemblyFixture.cs
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/XunitTestFrameworkWithAssemblyFixture.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
TechTalk.SpecFlow/Bindings/Discovery/RuntimeBindingRegistryBuilder.cs
TechTalk.SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
Tests/TechTalk.SpecFlow.GeneratorTests/UnitTestProvider/XUnit2TestGeneratorProviderTests.cs
Tests/TechTalk.SpecFlow.Specs/Features/Contexts/InjectoContextToHooks.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/CucumberMessages/ScenarioSteps.cs
Tests/TechTalk.SpecFlow.Specs/Support/Hooks.cs

use xunit integration to trigger AfterTestRun hook

---

TechTalk.SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/build/SpecFlow.targets

I was browsing through the issues of this amazing tool (as you do on Saturday mornings) and I noticed that @SabotageAndi more or less had written the code to fix this problem in the #1315 issue. 
As I ran into this a few times while updating [SpecFlow.Assists.Dynamic](http://www.marcusoft.net/SpecFlow.Assist.Dynamic/) I thought that other people would be interested in this too. 
But really ... this is all @SabotageAndi stuff. Thank you
- [  X ] Bug fix (non-breaking change which fixes an issue).
- [ X ] New feature (non-breaking change which adds functionality).
I am a little unsure if this will need updates to the documentation. Please advice

Added .targets for fix to NuGet package - fixes #1315

---

build.ps1
build.yml
global.json

use final .NET Core 3 SDK

---

TechTalk.SpecFlow/CucumberMessages/CucumberMessageFactory.cs
TechTalk.SpecFlow/CucumberMessages/TestResultPartsFactory.cs
TechTalk.SpecFlow/DateTimeExtensions.cs
TechTalk.SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/CucumberMessageFactoryTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/CucumberMessageSenderTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/Sinks/ProtobufFileSinkOutputTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/TestResultPartFactoryTestsAmbiguous.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/TestResultPartFactoryTestsFailed.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/TestResultPartFactoryTestsPassed.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/TestResultPartFactoryTestsPending.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/TestResultPartFactoryTestsSkipped.cs
Tests/TechTalk.SpecFlow.RuntimeTests/CucumberMessages/TestResultPartFactoryTestsUndefined.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/DateTimeExtensionsTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/TechTalk.SpecFlow.RuntimeTests.csproj

update cucumber messages to 6.0.1

---

azure-pipelines.yml
build.ps1
build.yml

Add 'AppInsightsInstrumentationKey' as parameter to the Build

Update azure-pipelines.yml for Azure Pipelines

---

build.yml

fix Azure DevOps Build Pipelines for PRs

---

build.yml

Update the .NET Core installer task

update .NET Core installer task

---

Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/SpecFlow.MsTest.targets
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/SpecFlow.NUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/SpecFlow.xUnit.targets
Tests/TechTalk.SpecFlow.GeneratorTests/MSBuildTask/GenerateFeatureFileCodeBehindTaskTests.cs
changelog.txt

Fixes https://github.com/techtalk/SpecFlow/issues/1846

Fix empty root namespace regression

---

Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/MSTest.AssemblyHooks.template.cs
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/NUnit.AssemblyHooks.template.cs

Fix issue #1864 by reordering using directives

---

Dockerfile
TechTalk.SpecFlow.Generator/CodeDom/CodeDomHelper.cs

Minor changes, Fix Typo, Update Docker Image

---

SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.props
SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.tasks
changelog.txt

Should fix https://github.com/SpecFlowOSS/SpecFlow/issues/1699

Import MSBuild tasks file only once

---

Directory.Build.props
Installer/TechTalk.SpecFlow.NUnit.Runners/TechTalk.SpecFlow.NUnit.Runners.csproj
Plugins/SpecFlow.Autofac.SpecFlowPlugin/SpecFlow.Autofac.SpecFlowPlugin.csproj
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin.csproj
Plugins/TechTalk.SpecFlow.MSTest.SpecFlowPlugin/TechTalk.SpecFlow.MSTest.SpecFlowPlugin.csproj
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin.csproj
Plugins/TechTalk.SpecFlow.NUnit.SpecFlowPlugin/TechTalk.SpecFlow.NUnit.SpecFlowPlugin.csproj
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin.csproj
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/TechTalk.SpecFlow.xUnit.SpecFlowPlugin.csproj
SpecFlow.Tools.MsBuild.Generation/SpecFlow.Tools.MsBuild.Generation.csproj
TechTalk.SpecFlow.Generator/TechTalk.SpecFlow.Generator.csproj
TechTalk.SpecFlow.Parser/TechTalk.SpecFlow.Parser.csproj
TechTalk.SpecFlow.Utils/TechTalk.SpecFlow.Utils.csproj
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj

update sourcelink and referenceassemblies packages

---

README.md

Changed links to https in Readme

---

TechTalk.SpecFlow/Assist/TEHelpers.cs
TechTalk.SpecFlow/Assist/TableExtensionMethods.cs
changelog.txt

Small performance improvements, like setting the initial capacity and reduce the amount of relection

Small performance improvements for `table.CreateSet` and `table.CreateInstance`

---

.github/pull_request_template.md

Extended 'types of changes' in PR template

---

index.html

Just another http/https. Note this is targeting gh-pages (which is good!)

let https://specflowoss.github.io/SpecFlow/ redirect to https of specflow.org

---

Directory.Build.props
Plugins/SpecFlow.Autofac.SpecFlowPlugin/SpecFlow.Autofac.nuspec
Plugins/SpecFlow.Autofac.SpecFlowPlugin/build/SpecFlow.Autofac.targets
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/SpecFlow.MsTest.targets
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/SpecFlow.NUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/SpecFlow.xUnit.nuspec
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/SpecFlow.xUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/TechTalk.SpecFlow.xUnit.SpecFlowPlugin.csproj
TechTalk.SpecFlow/SpecFlow.nuspec
Tests/TechTalk.SpecFlow.GeneratorTests/Data/CSProj_New/sampleCsProjectfile.csproj
Tests/TechTalk.SpecFlow.GeneratorTests/Data/CSProj_NewComplex/sampleCsProjectfile.csproj
Tests/TechTalk.SpecFlow.GeneratorTests/Data/CSProj_NewWithExclude/sampleCsProjectfile.csproj
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/MultiFeatureGenerator.cs
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/TestRunCombinations.cs
changelog.txt

Update .NET Framework version from net45 to net461

---

Directory.Build.props
Installer/TechTalk.SpecFlow.CustomPlugin/SpecFlow.CustomPlugin.nuspec
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/SpecFlow.MSTest.nuspec
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/SpecFlow.MsTest.targets
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/SpecFlow.NUnit.nuspec
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/SpecFlow.NUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/SpecFlow.xUnit.nuspec
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/SpecFlow.xUnit.targets
SpecFlow.Tools.MsBuild.Generation/SpecFlow.Tools.MsBuild.Generation.nuspec
SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.props
Tests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests.csproj
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
changelog.txt

Downgrade Generator plugins and MSBuild.Generation to net461

---

Tests/TechTalk.SpecFlow.Specs/Drivers/CucumberMessages/MessageValidationDriver.cs
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/CucumberMessages/TestCaseStartedSteps.cs
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/CucumberMessages/TestSuiteSteps.cs

Avoid cucumber messages test failure due to hard-coded version number

---

TechTalk.SpecFlow/Analytics/AnalyticsEventProvider.cs

Extend the build server detection and reporting

---

Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/SpecFlow.xUnit.nuspec
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/TechTalk.SpecFlow.xUnit.SpecFlowPlugin.csproj

Downgrade to xUnit 2.4.0 in runtime plugin because VS Templates are using this

---

changelog.txt
version.json

Update version to 3.3 and update changelog

---

docs/Installation/Requirements.md
docs/index.rst

add requirements to documentation

---

azure-pipelines.yml

update trigger definition

---

docs/Bindings/Bindings.md
docs/Bindings/Hooks.md
docs/Bindings/Scoped-Step-Definitions.md
docs/Bindings/Step-Definitions.md
docs/index.rst

improve binding documentation

---

Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/SpecFlow.MSTest.nuspec
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/SpecFlow.NUnit.nuspec
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/SpecFlow.xUnit.nuspec

Add  "SpecFlow.Tools.MSBuild.Generation" dependency to SpecFlow.xUnit, NUnit, MSTest packages

---

docs/Installation/Requirements.md

add hint for project filesystem depth

---

docs/Bindings/SpecFlow-Assist-Helpers.md

small fixes for assist documentation

---

Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj

Add missing bindings for Cucumber messages related scenarios

---

Tests/TechTalk.SpecFlow.GeneratorTests/FileFilterTests.cs

Unit test code change to enable unit test execution on non-windows agents.

Ignore FileFilterTests on non-windows platforms

---

changelog.txt

update changelog for release after 3.3.30

---

docs/Guides/UpgradeSpecFlow2To3.md
docs/Installation/NuGet-Packages.md
docs/Installation/SpecFlow-and-.NET-Core.md
docs/Tools/Generate-Tests-From-MsBuild.md

adjust new dependency of `SpecFlow.Tools.MSBuild.Generation`

Adjust documentation for changes after 3.3.30

---

SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.targets
TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
TechTalk.SpecFlow/Plugins/RuntimePluginEventArgs.cs
TechTalk.SpecFlow/Plugins/RuntimePluginEvents.cs
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
changelog.txt
docs/Extend/Plugins.md
version.json

8233 testrunend event

---

TechTalk.SpecFlow/Assist/ValueRetrievers/NullValueRetriever.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/NullValueRetrieverTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/ValueRetrieverTestsUtils.cs
changelog.txt

add in #1928 removed NullValueRetriever back

---

SpecFlow.Tools.MsBuild.Generation/GenerateFeatureFileCodeBehindTaskContainerBuilder.cs
TechTalk.SpecFlow.Generator/DefaultDependencyProvider.cs
TechTalk.SpecFlow.Generator/Project/MsBuildProjectReader.cs
TechTalk.SpecFlow/Configuration/ConfigurationLoader.cs
TechTalk.SpecFlow/Configuration/ISpecFlowJsonLocator.cs
TechTalk.SpecFlow/Configuration/SpecFlowJsonLocator.cs
TechTalk.SpecFlow/Infrastructure/DefaultDependencyProvider.cs
Tests/TechTalk.SpecFlow.GeneratorTests/MsBuildProjectReaderTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Configuration/AppConfigTests.cs

Introduce SpecFlowJsonLocator

---

TechTalk.SpecFlow/Analytics/AppInsights/AppInsightsEventSerializer.cs
TechTalk.SpecFlow/Analytics/AppInsights/AppInsightsEventTelemetry.cs
TechTalk.SpecFlow/Analytics/AppInsights/IAppInsightsEventSerializer.cs
TechTalk.SpecFlow/Analytics/HttpClientAnalyticsTransmitterSink.cs
TechTalk.SpecFlow/Analytics/IAnalyticsTransmitterSink.cs
Tests/TechTalk.SpecFlow.GeneratorTests/Analytics/AnalyticsTransmitterTests.cs

Option to override AI instrumentation key

---

docs/Getting-Started/Getting-Started-With-A-New-Project.md
docs/requirements.txt

fix pictures

---

TechTalk.SpecFlow/Analytics/AnalyticsEventProvider.cs

Further improve list of the detected build servers. Source https://www.guru99.com/top-20-continuous-integration-tools.html

Extend the build server detection

---

version.json

Remove beta flag

---

TechTalk.SpecFlow.Generator/Generation/UnitTestFeatureGenerator.cs
TechTalk.SpecFlow.Generator/TestGenerator.cs
TechTalk.SpecFlow.Parser/IGherkinParser.cs
TechTalk.SpecFlow.Parser/SpecFlowDocument.cs
TechTalk.SpecFlow.Parser/SpecFlowDocumentLocation.cs
TechTalk.SpecFlow.Parser/SpecFlowGherkinParser.cs
TechTalk.SpecFlow/FeatureInfo.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorBasicsTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/UnitTestProvider/NUnit3GeneratorProviderTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/UnitTestProvider/XUnit2TestGeneratorProviderTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestThreadContextTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/ScenarioStepContextTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/StepExecutionTestsBase.cs
Tests/TechTalk.SpecFlow.RuntimeTests/TestObjectFactories.cs
Tests/TechTalk.SpecFlow.RuntimeTests/TestRunnerManagerRunnerCreationTests.cs
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/MultiFeatureGenerator.cs
Tests/TechTalk.SpecFlow.Specs/Drivers/Parser/ParserDriver.cs
changelog.txt

- Extended FeatureInfo with FolderPath information
- Extended SpecFlowDocument with DocumentLocation that contains both the SourceFilePath and the FeatureFolderPath
- Changed IGherkinParser.Parse to expect a SpecFlowDocumentLocation (instead of the SourceFilePath string only)

Extend FeatureInfo with FolderPath information

---

changelog.txt
version.json

Update SpecFlow version to 3.4

---

TechTalk.SpecFlow.Generator/TestGeneratorFactory.cs

Update GeneratorVersion to 3.4

---

TechTalk.SpecFlow/Analytics/AnalyticsEventProvider.cs

Add Codefresh detection

---

docs/Getting-Started/Getting-Started-With-A-New-Project.md

The expectedResult variable is not defined.

Wrong variable referenced

---

docs/Integrations/xUnit.md

fixed typo

---

docs/Tools/Visual-Studio-Integration-Navigation-Features.md

fix VS Nav headlines

---

docs/Execution/SkippingScenarios.md
docs/index.rst

add documentation how to skip a scenario

---

TechTalk.SpecFlow/PlatformCompatibility/MonoHelper.cs
TechTalk.SpecFlow/Table.cs

Null check and common length condition check 

---

TechTalk.SpecFlow/Assist/RowExtensionMethods.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/RowExtensionMethodTests.cs
changelog.txt

Made `GetBoolean` case-insensitive.
Closes #2136

Make GetBoolean case insensitive

---

docs/Integrations/Browserstack.md

Fixing Code sample link in Browserstack.md

---

docs/Installation/Installation.md

updated link

---

docs/Bindings/SpecFlow-Assist-Helpers.md
docs/Extend/Plugins.md
docs/Getting-Started/Getting-Started-With-An-Example.md
docs/Installation/Installation.md

Fixed typos and mistakes related to inconsistent or misspelled entity references in the documentation pages

Resolve typos and mistakes in documentation

---

CONTRIBUTING.md
README.md

So there was a typo that "critical" was spelled as "criticial".
And in the readme file `If you are interested in contributing, there are some useful information on this page:`
information is singular so changed are to is
To be honest, Its a really small pr and might even look like spam but the change is needed

Minor Typo Fix in Contributing.md and in Readme

---

changelog.txt

Fixed typos in this .txt file.
also there were grammatical mistakes like new line should start with capital alphabet so covered that too

Resolved Typos and mistakes in changelog.txt

---

docs/Integrations/Autofac.md
docs/Integrations/SpecFlow.Autofac.md
docs/index.rst

Changes for Documentation request: SpecFlow.Autofac #2128(Patch 2)

---

docs/Guides/PageObjectModel.md
docs/index.rst

Docs for using the PageObject Pattern with Selenium

---

Directory.Build.props

use latest lang version

---

Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/ExternalDataFeaturePatcher.cs
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/ExternalDataGeneratorPlugin.cs
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/ExternalDataTestGenerator.cs
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/SpecFlow.ExternalData.SpecFlowPlugin.csproj
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/SpecFlow.ExternalData.nuspec
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/TestDataProvider.cs
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/build/SpecFlow.ExternalData.props
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/build/SpecFlow.ExternalData.targets
Plugins/SpecFlow.ExternalData/sample/ExternalDataSample/Features/Comments.feature
Plugins/SpecFlow.ExternalData/sample/ExternalDataSample/Features/Email.feature
Plugins/SpecFlow.ExternalData/sample/ExternalDataSample/Specs.csproj
Plugins/SpecFlow.ExternalData/sample/ExternalDataSample/Specs.sln
Plugins/SpecFlow.ExternalData/sample/ExternalDataSample/Steps/CommentBindings.cs
Plugins/SpecFlow.ExternalData/sample/ExternalDataSample/Steps/RegistrationBindings.cs
Plugins/SpecFlow.ExternalData/sample/ExternalDataSample/testdata.json
Plugins/SpecFlow.ExternalData/sample/nuget.config
TechTalk.SpecFlow.sln
version.json

SpecFlow external data plugin

---

docs/Bindings/Use-Bindings-from-External-Assemblies.md
docs/Installation/Configuration.md

Add `specflow.json` example how to configure additional step assemblies

Improve docs of additional step assemblies

---

Tests/TechTalk.SpecFlow.Specs/Features/UnitTestProviderSpecific/MsTest/DeploymentItem.feature

enable feature for .NET Core

---

docs/Installation/Configuration.md

Added further information about SpecFlow configuration (specflow.json).

Extend public docs

---

TechTalk.SpecFlow/FeatureContext.cs
TechTalk.SpecFlow/ScenarioContext.cs

improve link to migration guide for ScenarioContext.Current and FeatureContext.Current

---

.github/ISSUE_TEMPLATE/bug_report.md
Build/Versioning.targets
TechTalk.SpecFlow.Generator/TestGeneratorFactory.cs
version.json

change version number to 3.5

---

.github/ISSUE_TEMPLATE/bug_report.md
Directory.Build.props
Directory.Build.targets
Installer/TechTalk.SpecFlow.CustomPlugin/SpecFlow.CustomPlugin.nuspec
Plugins/SpecFlow.Autofac.SpecFlowPlugin/SpecFlow.Autofac.nuspec
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/SpecFlow.MSTest.nuspec
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/SpecFlow.NUnit.nuspec
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/SpecFlow.xUnit.nuspec
SpecFlow.Tools.MsBuild.Generation/SpecFlow.Tools.MsBuild.Generation.csproj
SpecFlow.Tools.MsBuild.Generation/SpecFlow.Tools.MsBuild.Generation.nuspec
TechTalk.SpecFlow.Generator/TechTalk.SpecFlow.Generator.csproj
TechTalk.SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
Tests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests.csproj
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/MultiFeatureGenerator.cs
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/TestRunCombinations.cs
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
build.yml

Netcoreapp5

---

docs/index.rst

Add links to the new Getting Started Step By Step Guide

---

Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ExampleEntities/Person.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/TableHelperExtensionMethods/RecordSupport.cs
docs/Bindings/SpecFlow-Assist-Helpers.md
docs/index.rst

Record support

---

docs/Bindings/FeatureContext.md
docs/Bindings/ScenarioContext.md

add migration guide for Scenario/FeatureContext.Current

---

.github/ISSUE_TEMPLATE/bug_report.md

remove VS2015 support

---

docs/Bindings/Scoped-Step-Definitions.md

Fix Scope docs

---

TechTalk.SpecFlow/build/SpecFlow.targets
changelog.txt

Copy specflow.json to the output directory (if exists)

---

.gitignore
Directory.Build.rsp
TechTalk.SpecFlow.sln

Add MSBuild response file to reduce local setup

---

docs/Extend/Value-Retriever.md

Add registration information to ValueRetriever documentation

---

TechTalk.SpecFlow/ErrorHandling/PendingStepException.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Exceptions/PendingStepExceptionTests.cs
changelog.txt
docs/Bindings/ScenarioContext.md
docs/Execution/Mark-Steps-As-Not-Implemented.md
docs/index.rst

Add custom message to PendingStepException

---

Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/SpecFlow.ExternalData.SpecFlowPlugin.csproj
Plugins/SpecFlow.ExternalData/sample/ExternalDataSample/Specs.csproj
changelog.txt

Update SpecFlow.ExternalData to use SpecFlow 3.5

---

Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj

build Specs for correct TFMs depending on MSBuild Runtime

---

version.json

Update version number to 3.6-beta

---

azure-pipelines.yml

CI build should trigger only for master

---

Directory.Build.props
Plugins/SpecFlow.Autofac.SpecFlowPlugin/SpecFlow.Autofac.nuspec
Plugins/SpecFlow.Windsor.SpecFlowPlugin/SpecFlow.Windsor.nuspec
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/SpecFlow.MSTest.nuspec
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/SpecFlow.NUnit.nuspec
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/SpecFlow.xUnit.nuspec
SpecFlow.Tools.MsBuild.Generation/GenerateFeatureFileCodeBehindTaskExecutor.cs
SpecFlow.Tools.MsBuild.Generation/IMSBuildTaskAnalyticsTransmitter.cs
SpecFlow.Tools.MsBuild.Generation/MSBuildTaskAnalyticsTransmitter.cs
TechTalk.SpecFlow.Generator/Interfaces/ProjectPlatformSettings.cs
TechTalk.SpecFlow.Generator/Interfaces/TestGenerationError.cs
TechTalk.SpecFlow.Generator/RemotableGeneratorClass.cs
TechTalk.SpecFlow.Generator/TechTalk.SpecFlow.Generator.csproj
TechTalk.SpecFlow/Analytics/AnalyticsEventProvider.cs
TechTalk.SpecFlow/Infrastructure/ContextManager.cs
TechTalk.SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/Steps.cs
Templates/TechTalk.SpecFlow.Templates.DotNet/TechTalk.SpecFlow.Templates.DotNet.csproj
Tests/TechTalk.SpecFlow.GeneratorTests/MSBuildRelativePathParserTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/MsBuildProjectReaderTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorTestsBase.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TestUpToDateCheckerTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/CreateInstanceHelperMethodTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/DateTimeOffsetValueRetrieverTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/WorkingExampleOfValueRetrieverAndComparerAddition.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/AsyncHelperTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/StepTransformationTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/StepsTest.cs

Remove warnings from source

---

TechTalk.SpecFlow.Generator/TestGenerator.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TestGeneratorErrorsTests.cs
changelog.txt

Do not show generation error in case of empty feature file

---

Tests/TechTalk.SpecFlow.GeneratorTests/TechTalk.SpecFlow.GeneratorTests.csproj
Tests/TechTalk.SpecFlow.PluginTests/TechTalk.SpecFlow.PluginTests.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/TechTalk.SpecFlow.RuntimeTests.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/TraceListenerQueueTests.cs
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
build.yml

Fix flaky test and netcoreapp2.1 Unit Test runs

---

build.yml

Use latest .NET 5 SDK + Update submodules

---

Tests/TechTalk.SpecFlow.Specs/Features/Hooks/HookParameterInjection.feature
docs/Bindings/Hooks.md

* No production code changed / no changelog entry
* Added scenarios for hook parameter injection
* Added documentation for hook parameter injection

Documentation: Hook parameter injection

---

azure-pipelines.yml

Batch changes while a build is in progress

---

TechTalk.SpecFlow/Bindings/StepArgumentTypeConverter.cs
Tests/TechTalk.SpecFlow.Specs/Features/Execution/StepArgumentTransformations.feature
changelog.txt

Correctly handle Table argument step transformations when multiple matching transformation exists

---

TechTalk.SpecFlow/Infrastructure/ContainerBuilder.cs
TechTalk.SpecFlow/Infrastructure/DefaultDependencyProvider.cs
TechTalk.SpecFlow/Infrastructure/ITestAssemblyProvider.cs
TechTalk.SpecFlow/Infrastructure/TestAssemblyProvider.cs
TechTalk.SpecFlow/Plugins/IRuntimePluginLocator.cs
TechTalk.SpecFlow/Plugins/RuntimePluginLocator.cs
Tests/TechTalk.SpecFlow.PluginTests/RuntimePluginLocatorTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Container/RuntimePluginLocatorTests.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/PluginTests.cs
changelog.txt
docs/Extend/Plugins.md

Search for RuntimePlugins in the TestAssembly

---

TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
Tests/TechTalk.SpecFlow.Specs/Features/Hooks/HookErrorHandling.feature
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/BindingSteps.cs
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/ExecutionResultSteps.cs
changelog.txt
docs/Bindings/Hooks.md

We are now explicitly handle errors during BeforeScenarioHooks and set the `ScenarioExecutionStatus` and `TestError`. 
Fixes #1646

Handle errors in BeforeScenarioHooks 

---

changelog.txt
version.json

Change version to 3.6

---

.github/ISSUE_TEMPLATE/bug_report.md

Update issue template to 3.6

---

Tests/TechTalk.SpecFlow.Specs/specflow.json

Fix navigation from test explorer to feature file

---

docs/Bindings/Scoped-Step-Definitions.md

Update Scope docs: Different level Scope behavior

---

docs/Bindings/Bindings.md
docs/Bindings/Step-Definitions.md

Update Binding docs: Mention required BindingAttribute

---

TechTalk.SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
changelog.txt
version.json

Thread-safe object resolution with BoDi (beta)

---

docs/Bindings/Step-Definitions.md

- [x ] Other (docs, build config, etc)

added [Obsolete} attribute to docs

---

TechTalk.SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
version.json

Update BoDi to 1.5.0 (finalize version 1.5.0-alpha2)
Set SpecFlow version to 3.7 (finalize version 3.7-beta)

Update BoDi to v1.5.0 (thread-safe object resolution)

---

docs/Installation/Configuration.md

Docs: Fix typo in Configuration

---

docs/Extend/Decorators.md
docs/Extend/Plugins.md

update Plugin documentation

---

TechTalk.SpecFlow.Generator/DefaultDependencyProvider.cs
TechTalk.SpecFlow.Generator/UnitTestConverter/IgnoreDecorator.cs
TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
Tests/TechTalk.SpecFlow.Specs/Features/Hooks/HookSupport.feature
changelog.txt

Simplify the ignore tag behavior by generating again the test framework specific ignore attributes.
Related to https://github.com/SpecFlowOSS/SpecFlow/issues/2234
Notes:
* Removed scenario "TestCaseFinished message with status Skipped is send, if the scenario is ignored" from https://github.com/SpecFlowOSS/cucumber/blob/cucumber-messages/Specification/cucumber-messages/specs/TestCaseFinished.feature, because tests ignored by attribute are not executed (not started/finished)
* Changed what we expect in the TRX result for ignored tests https://github.com/SpecFlowOSS/SpecFlow.TestProjectGenerator/blob/master/SpecFlow.TestProjectGenerator/TRXParser.cs
* Simplified assertion in HookSupport.feature "For ignored Scenarios no Scenario Hooks are called", because for the edge case when all …

Ignore tag handling: generate test framework specific ignore attributes

---

TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
changelog.txt

Cleanup scenario context even after an AfterScenario hook error

---

docs/Bindings/ScenarioContext.md

Fix Wording in ScenarioContext docs

---

docs/_templates/footer.html

added new footer to _template

---

.github/ISSUE_TEMPLATE/bug_report.md

Update issue template to SpecFlow 3.7 and remove non LTS frameworks

---

TechTalk.SpecFlow/Analytics/AnalyticsEventProvider.cs

Detect octopus tentacle/worker

---

TechTalk.SpecFlow/Assist/ValueRetrievers/BoolValueRetriever.cs
Tests/TechTalk.SpecFlow.RuntimeTests/AssistTests/ValueRetrieverTests/BoolValueRetrieverTests.cs
changelog.txt
docs/_templates/breadcrumbs.html

- [x ] New feature (non-breaking change which adds functionality).
- [x ] I've added tests for my code. (most of the time mandatory)
- [x ] I have added an entry to the changelog. (mandatory)

Gh1901 Add support multilingual bool value

---

docs/Execution/Parallel-Execution.md

Fixed link and Notes

---

docs/Execution/Parallel-Execution.md
docs/Extend/Plugins.md
docs/index.rst
docs/legacy/CodedUI.md
docs/legacy/Plugins-(Legacy).md

Legacy pages moved + structure

---

docs/Rider/rider-features.md
docs/Rider/rider-installation.md
docs/visualstudio/Generating-Skeleton-Code.md
docs/visualstudio/Visual-Studio-Integration-Editing-Features.md
docs/visualstudio/Visual-Studio-Integration-Navigation-Features.md
docs/visualstudio/Visual-Studio-Integration.md
docs/visualstudio/Visual-Studio-Test-Explorer-Support.md
docs/visualstudio/visual-studio-installation.md

updated toc tree and naming

---

TechTalk.SpecFlow.Generator/TestGeneratorFactory.cs

In order to avoid code-behind file version issues
we will automatically update the SpecFlow Generator Version and replace it with the Runtime version
whereas currently, the SpeFlow Generator Version needs to be updated manually for each new release (which is prone to errors)

Use assembly version as generator version

---

docs/_templates/layout.html

added google tag js

---

Templates/TechTalk.SpecFlow.Templates.DotNet/TechTalk.SpecFlow.Templates.DotNet.csproj
Templates/TechTalk.SpecFlow.Templates.DotNet/templates/SpecFlowProject/.template.config/template.json
Templates/TechTalk.SpecFlow.Templates.DotNet/templates/SpecFlowProject/Template.csproj

Keep the nuget package versions current in the dotnet templates.

Auto-update versions in dotnet new templates

---

docs/_templates/layout.html

add GA back in

---

docs/index.rst

fix logo image

---

TechTalk.SpecFlow/Analytics/AnalyticsTransmitter.cs
TechTalk.SpecFlow/Analytics/IAnalyticsTransmitter.cs
TechTalk.SpecFlow/CucumberMessages/CucumberMessageSender.cs
TechTalk.SpecFlow/Infrastructure/TestExecutionEngine.cs
Tests/TechTalk.SpecFlow.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs

Instead of computing an expensive parameter, check beforehand whether it is needed at all.

reduce overhead when analytics is disabled

---

TechTalk.SpecFlow/Analytics/HttpClientAnalyticsTransmitterSink.cs
TechTalk.SpecFlow/Analytics/HttpClientWrapper.cs
TechTalk.SpecFlow/Tracing/TraceListenerQueue.cs
changelog.txt

Some (not always used) classes initialize expensive fields that could be lazily initialized to speed up the case where they're not used. (Not used e.g. HTTPClient is only used when analytics is on)
Before/After
HTTPClient
HttpClientAnalyticsTransmitterSink
TraceListenerQueue

reduce ctor work for classes not used all the time

---

TechTalk.SpecFlow/BindingSkeletons/StepTextAnalyzer.cs
Tests/TechTalk.SpecFlow.RuntimeTests/BindingSkeletons/StepTextAnalyzerTests.cs
changelog.txt

Fixed bug in StepTextAnalyzer with empty string parameters

---

Templates/TechTalk.SpecFlow.Templates.DotNet/TechTalk.SpecFlow.Templates.DotNet.csproj
Templates/TechTalk.SpecFlow.Templates.DotNet/templates/SpecFlowProject/.template.config/template.json

Fix the package references in the dotnet new template

---

SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.targets

Change the default MSBuild EmbeddedResource naming to use the file's [Identity](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-well-known-item-metadata?view=vs-2019) instead.

Embed feature files with it's Identity

---

docs/Getting-Started/Getting-Started-With-An-Example.md
docs/Guides/PageObjectModel.md
docs/index.rst

new guides structure

---

docs/index.rst

fixed typo in home page

---

version.json

Change to 3.8-beta

---

build.yml
nightly-build.yml

It would be enough to run WhiteSource Bolt only once a day.
Also we could get rid of the timeout issues it has since the latest update.

Move WhiteSourceBolt task to a nightly build

---

Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/MSTest.AssemblyHooks.template.vb

Create and use MsTestContainerBuilder in the VB AssemblyHook template too

---

nightly-build.yml

Don't trigger nightly build for PRs

---

changelog.txt
version.json

Update version to 3.8

---

TechTalk.SpecFlow/Infrastructure/SpecFlowAttachmentHandler.cs
TechTalk.SpecFlow/Infrastructure/SpecFlowOutputHelper.cs
Tests/TechTalk.SpecFlow.Specs/StepDefinitions/ExecutionResultSteps.cs
changelog.txt

Route output API messages to tool output (instead of test output)

---

.github/ISSUE_TEMPLATE/impl_feature_request.yml

Issue template to discuss feature implementation details

---

CONTRIBUTING.md

add paragraph to discuss how to implement new features

---

docs/Bindings/ScenarioContext.md
docs/conf.py
docs/index.rst
docs/outputapi/outputapi.md

output api feedback

---

docs/Bindings/Bindings.md
docs/Bindings/Step-Definitions.md

added note on binding being global

---

CONTRIBUTING.md

added note on naming convention in contributions

---

Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/SpecFlow.ExternalData.SpecFlowPlugin.csproj
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/TestDataProvider.cs
TechTalk.SpecFlow/Analytics/AppInsights/AppInsightsEventSerializer.cs
TechTalk.SpecFlow/Configuration/JsonConfig/JsonConfigurationLoader.cs
TechTalk.SpecFlow/Configuration/JsonConfig/TraceElement.cs
TechTalk.SpecFlow/SpecFlow.nuspec
TechTalk.SpecFlow/TechTalk.SpecFlow.csproj
Tests/TechTalk.SpecFlow.Specs/Drivers/Parser/ParserDriver.cs
changelog.txt
nuget.config
version.json

Replace Utf8Json with SpecFlow.Internal.Json

---

docs/Getting-Started/Getting-Started-With-An-Example.md
docs/Guides/multiplebrowser.md
docs/index.rst

UI docs moved from old website to docs

---

docs/_templates/breadcrumbs.html

added editor link to breadcrumbs

---

docs/visualstudio/Visual-Studio-Integration-Editing-Features.md

wording updated

---

docs/Gherkin/Gherkin-Reference.md

Update to Gherkin-Reference.md, added some additional info regarding markdown syntax in feature files.
- [ x ] Other (docs, build config, etc)
- [ x ] I have updated the documentation accordingly.

added markdown section to Gherkin-Reference.md

---

TechTalk.SpecFlow.Parser/SemanticValidators/DuplicateExamplesColumnHeadersValidator.cs
TechTalk.SpecFlow.Parser/SpecFlowGherkinParser.cs
Tests/TechTalk.SpecFlow.GeneratorTests/ScenarioOutlineParserTests.cs
changelog.txt

Add semantic validator for duplicate Example column header names

---

docs/Gherkin/Gherkin-Reference.md

note on duplicate table headers

---

docs/_templates/footer.html

updated faq footer link

---

docs/Integrations/Browserstack.md

browser stack action

---

changelog.txt
docs/Extend/Available-Plugins.md

Update Available-Plugins.md
Move Specflow.DSL out of outdated section to other plugins section

Move Specflow.DSL out of outdated section

---

README.md
Tests/TechTalk.SpecFlow.Specs/Features/Build systems.feature
Tests/TechTalk.SpecFlow.Specs/Features/Hooks/HookErrorHandling.feature
Tests/TechTalk.SpecFlow.Specs/Features/LanguageSupport.feature
Tests/TechTalk.SpecFlow.Specs/Features/MultipleSpecsProjects.feature
build.yml
nightly-build.yml

Net6 support

---

docs/Installation/Configuration.md

Fixed a typo

---

docs/Bindings/Calling-Steps-from-Step-Definitions.md

Add link to the Calling Step Discussion

---

Templates/TechTalk.SpecFlow.Templates.DotNet/templates/SpecFlowProject/.template.config/template.json

Remove SpecFlow+ Runner from .NET CLI Templates

---

docs/_static/js/serversidetracking.js
docs/conf.py

add server side tracking to docs

---

Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/SpecFlow.ExternalData.SpecFlowPlugin.csproj
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/SpecFlow.ExternalData.nuspec

fix the packaging of the external data plugin for dotnet build

---

TechTalk.SpecFlow.sln
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/TestRunCombinations.cs
azure-pipelines.yml
build.yml

Use always .NET SDKs for building and running tests

---

docs/Bindings/SpecFlow-Assist-Helpers.md

- Rewrote the section for `CreateInstance<T>` to give a more complete explanation
- Added info about vertical and horizontal tables
- Formatted code consistently across the whole document
- Added a small section about comparing sets when order matters

Expanded explanations about methods to create and compare objects

---

SpecFlow.Tools.MsBuild.Generation/MSBuildTraceListener.cs
SpecFlow.Tools.MsBuild.Generation/WrappedGeneratorContainerBuilder.cs
TechTalk.SpecFlow.Generator/GeneratorContainerBuilder.cs

introduce a TraceListener for MSBuild Task

---

docs/Installation/Configuration.md

Added remark to point out usage of feature's specific #language

---

docs/Bindings/SpecFlow-Assist-Helpers.md
docs/requirements.txt
docs/vscode/vscode-debug.md

fix errors in doc build

---

docs/requirements.txt

fix readthedocs build again

---

Directory.Build.props
Installer/TechTalk.SpecFlow.CustomPlugin/SpecFlow.CustomPlugin.nuspec
Plugins/SpecFlow.Autofac.SpecFlowPlugin/SpecFlow.Autofac.nuspec
Plugins/SpecFlow.Autofac.SpecFlowPlugin/build/SpecFlow.Autofac.targets
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin.UnitTests/SpecFlow.ExternalData.SpecFlowPlugin.UnitTests.csproj
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/SpecFlow.ExternalData.nuspec
Plugins/SpecFlow.ExternalData/SpecFlow.ExternalData.SpecFlowPlugin/build/SpecFlow.ExternalData.targets
Plugins/SpecFlow.Windsor.SpecFlowPlugin/SpecFlow.Windsor.nuspec
Plugins/SpecFlow.Windsor.SpecFlowPlugin/build/SpecFlow.Windsor.targets
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/SpecFlow.MSTest.nuspec
Plugins/TechTalk.SpecFlow.MSTest.Generator.SpecFlowPlugin/build/SpecFlow.MsTest.targets
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/SpecFlow.NUnit.nuspec
Plugins/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin/build/SpecFlow.NUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/SpecFlow.xUnit.nuspec
Plugins/TechTalk.SpecFlow.xUnit.Generator.SpecFlowPlugin/build/SpecFlow.xUnit.targets
Plugins/TechTalk.SpecFlow.xUnit.SpecFlowPlugin/TechTalk.SpecFlow.xUnit.SpecFlowPlugin.csproj
SpecFlow.Tools.MsBuild.Generation/SpecFlow.Tools.MsBuild.Generation.nuspec
SpecFlow.Tools.MsBuild.Generation/build/SpecFlow.Tools.MsBuild.Generation.props
TechTalk.SpecFlow/SpecFlow.nuspec
Tests/TechTalk.SpecFlow.GeneratorTests/MSBuildRelativePathParserTests.cs
Tests/TechTalk.SpecFlow.GeneratorTests/TechTalk.SpecFlow.GeneratorTests.csproj
Tests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests/TechTalk.SpecFlow.MsBuildNetSdk.IntegrationTests.csproj
Tests/TechTalk.SpecFlow.PluginTests/TechTalk.SpecFlow.PluginTests.csproj
Tests/TechTalk.SpecFlow.RuntimeTests/TechTalk.SpecFlow.RuntimeTests.csproj
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/MultiFeatureGenerator.cs
Tests/TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin/TestRunCombinations.cs
Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj
changelog.txt
docs/Extend/Plugins.md
docs/Installation/Requirements.md

upgrade to .NET 4.6.2 and xUnit 2.1.4

---

docs/Extend/Available-Plugins.md

Promoted plugin for [ReportPortal](https://reportportal.io)

Added ReportPortal plugin

---

Tests/TechTalk.SpecFlow.RuntimeTests/Bindings/BindingInvokerTests.cs

This is just adding a new runtime test, so the tasks above are not applicable.

Add BindingInvokerTests with a sample test to show usage
